const test=require('node:test');const assert=require('node:assert/strict');const {AgentEngine}=require('../dist/agent-engine');const {AGENT_TOOLS}=require('../dist/agent-tools');
const context={category:'Game Development',topic:'Godot',subtopic:'Enemy AI',project:'3D_horror',technologies:['GDScript'],confidence:.9,evidence:[],recentTopics:['Godot']};const pref={id:'p',name:'Godot',category:'Game Development',strength:.9,confidence:.9,firstSeen:'2026-09-01',lastSeen:'2026-09-30',evidenceCount:4,totalSeconds:3600,updatedAt:'2026-09-30'};const rec={id:'r',type:'learn_topic',title:'Learn Enemy AI',description:'x',category:'Learning',reason:'related',confidence:.8,score:80,createdAt:'2026-09-30',sourceContext:'Game Development / Godot'};
function provider(content,shouldFail=false){let calls=0;return {isConfigured:()=>true,status:()=> 'configured',get calls(){return calls},async generateResponse(){calls++;if(shouldFail)throw new Error('network');return {content,confidence:.8,provider:'fake',model:'fake',createdAt:'2026-09-30'}}}}
test('AI disabled prevents provider calls',async()=>{const p=provider('{"responses":[]}');const r=await new AgentEngine().generateWithLLM(context,[],[pref],[rec],AGENT_TOOLS,undefined,'2026-09-30');assert.equal(r.length>0,true);assert.equal(p.calls,0)});
test('AI enabled allows provider calls',async()=>{const p=provider('{"responses":[{"title":"Grounded response","explanation":"Based on Godot context","confidence":0.8,"suggestedTool":"get_current_context","requiresConfirmation":false}]}');const r=await new AgentEngine().generateWithLLM(context,[],[pref],[rec],AGENT_TOOLS,p,'2026-09-30');assert.equal(p.calls,1);assert.equal(r[0].title,'Grounded response')});
test('missing provider falls back safely',async()=>{const r=await new AgentEngine().generateWithLLM(context,[],[pref],[rec],AGENT_TOOLS,undefined,'2026-09-30');assert.ok(r.length)});
test('provider failure falls back safely',async()=>{const r=await new AgentEngine().generateWithLLM(context,[],[pref],[rec],AGENT_TOOLS,provider('{}',true),'2026-09-30');assert.ok(r.length)});
test('structured response is validated',async()=>{const r=await new AgentEngine().generateWithLLM(context,[],[],[],AGENT_TOOLS,provider('{"responses":[{"title":"x","explanation":"y","confidence":2,"suggestedTool":"get_memory","requiresConfirmation":true}]}'),'2026-09-30');assert.equal(r[0].confidence,1);assert.equal(r[0].suggestedTool,'get_memory')});
test('unknown tool is rejected',async()=>{const r=await new AgentEngine().generateWithLLM(context,[],[],[],AGENT_TOOLS,provider('{"responses":[{"title":"x","explanation":"y","confidence":0.5,"suggestedTool":"execute_command","requiresConfirmation":true}]}'),'2026-09-30');assert.ok(r.every(x=>x.suggestedTool!=='execute_command'))});
test('invalid confidence is clamped',async()=>{const r=await new AgentEngine().generateWithLLM(context,[],[],[],AGENT_TOOLS,provider('{"responses":[{"title":"x","explanation":"y","confidence":-2,"suggestedTool":null,"requiresConfirmation":false}]}'),'2026-09-30');assert.equal(r[0].confidence,0)});
test('LLM cannot create unauthorized tool',async()=>{const r=await new AgentEngine().generateWithLLM(context,[],[],[],AGENT_TOOLS,provider('{"responses":[{"title":"x","explanation":"y","confidence":0.4,"suggestedTool":"open_file","requiresConfirmation":true}]}'),'2026-09-30');assert.equal(r[0].suggestedTool,null);assert.equal(r[0].requiresConfirmation,false)});
test('deterministic behavior still works',()=>{const r=new AgentEngine().generate(context,[],[pref],[rec],AGENT_TOOLS,'2026-09-30');assert.ok(r.length);assert.ok(r.every(x=>x.confidence>=0&&x.confidence<=1))});
