const test=require('node:test');const assert=require('node:assert/strict');const {MemoryEngine}=require('../dist/memory-engine');const {PreferenceEngine}=require('../dist/preference-engine');const {buildPersonalizationSummary}=require('../dist/personalization-engine');const {emptyFeedbackSummary}=require('../dist/feedback-engine');const {RecommendationEngine}=require('../dist/recommendation-engine');
const now=Date.parse('2026-09-30T18:00:00.000Z');const context={category:'Game Development',topic:'Godot',subtopic:'Navigation',project:'Horror',technologies:['Godot','GDScript'],confidence:.9,evidence:[],recentTopics:['Godot']};const obs=(at,minutes=60,ctx=context)=>({context:ctx,observedAt:new Date(at).toISOString(),durationSeconds:minutes*60});
function memory(overrides={}){return {id:'memory:Godot',type:'topic',name:'Godot',category:'Game Development',strength:.7,confidence:.7,firstSeen:new Date(now-10*86400000).toISOString(),lastSeen:new Date(now).toISOString(),evidenceCount:4,totalSeconds:4*3600,source:'test',metadataJson:JSON.stringify({observedDays:['2026-09-10','2026-09-20','2026-09-29','2026-09-30'],dailyEvidence:{'2026-09-10':1,'2026-09-20':1,'2026-09-29':2,'2026-09-30':2},timeBuckets:{evening:4},weekdayEvidence:4,weekendEvidence:0,sessionCount:4,shortSessions:1,longSessions:3,projects:['Horror'],technologies:['Godot','GDScript'],topic:'Godot',project:'Horror'}),...overrides};}
test('preference requires repeated direct evidence',()=>{const e=new PreferenceEngine();assert.equal(e.update([], [memory({evidenceCount:1})], new Date(now).toISOString()).length,0);assert.ok(e.update([], [memory()], new Date(now).toISOString()).some(p=>p.name==='Godot'))});
test('preference evidence and confidence are bounded and explainable',()=>{const p=new PreferenceEngine().update([], [memory()], new Date(now).toISOString())[0];assert.ok(p.confidence>=0&&p.confidence<=1);assert.ok(p.strength>=0&&p.strength<=1);assert.ok(p.distinctDays>=4);assert.ok(p.evidenceSummary.includes('4 sessions'));assert.ok(p.evidenceSummary.includes('hours total'));assert.ok(!p.evidenceSummary.includes('window title'))});
test('preference strengthens with duration and distinct days',()=>{const e=new PreferenceEngine();const short=memory({evidenceCount:2,totalSeconds:300,metadataJson:JSON.stringify({observedDays:['2026-09-30'],dailyEvidence:{'2026-09-30':2}})});const long=memory();assert.ok(e.update([], [long], new Date(now).toISOString())[0].confidence>e.update([], [short], new Date(now).toISOString())[0].confidence)});
test('trends are deterministic',()=>{const rising=memory({metadataJson:JSON.stringify({observedDays:['2026-09-10','2026-09-20','2026-09-29'],dailyEvidence:{'2026-09-10':1,'2026-09-20':1,'2026-09-29':4}})});const declining=memory({lastSeen:new Date(now-2*86400000).toISOString(),metadataJson:JSON.stringify({observedDays:['2026-09-05','2026-09-10','2026-09-20'],dailyEvidence:{'2026-09-05':4,'2026-09-10':3,'2026-09-20':1}})});const e=new PreferenceEngine();assert.equal(e.update([], [rising], new Date(now).toISOString())[0].trend,'rising');assert.equal(e.update([], [declining], new Date(now).toISOString())[0].trend,'declining');const inactive=memory({lastSeen:new Date(now-100*86400000).toISOString()});assert.equal(e.update([], [inactive], new Date(now).toISOString())[0].trend,'inactive')});
test('time patterns use coarse buckets',()=>{const e=new MemoryEngine();let memories=e.update([],obs(Date.parse('2026-09-29T19:00:00Z')));memories=e.update(memories,obs(Date.parse('2026-09-30T20:00:00Z')));const p=new PreferenceEngine().update([],memories,new Date(now).toISOString()).find(x=>x.name==='Godot');assert.equal(p.timePattern.primaryBucket,'evening');assert.ok(p.timePattern.weekdayRatio>=.9);assert.equal(p.timePattern.sessionShape,'long')});
test('feedback is bounded and cannot create a preference alone',()=>{const feedback=emptyFeedbackSummary();feedback.byTopic.Godot={useful:10,not_useful:0,dismissed:0,ignored:0};const e=new PreferenceEngine();assert.equal(e.update([], [memory({evidenceCount:1})],new Date(now).toISOString(),feedback).length,0);const no=e.update([], [memory()],new Date(now).toISOString())[0];const yes=e.update([], [memory()],new Date(now).toISOString(),feedback).find(x=>x.name==='Godot');assert.ok(yes.strength>=no.strength);assert.ok(yes.strength-no.strength<=.05)});
test('preference decay weakens without deleting memory',()=>{const e=new PreferenceEngine();const original=e.update([], [memory()],new Date(now).toISOString())[0];const later=e.update([original], [], new Date(now+180*86400000).toISOString())[0];assert.ok(later.strength<original.strength);assert.equal(memory().name,'Godot')});
test('semantic support only supports an existing direct concept',()=>{const e=new PreferenceEngine();assert.equal(e.update([], [memory({evidenceCount:1})],new Date(now).toISOString(),undefined,{Pathfinding:.9}).length,0);const p=e.update([], [memory()],new Date(now).toISOString(),undefined,{Godot:.9})[0];assert.ok(p.strength>=0)});
test('recommendation reasons use stored aggregate evidence',()=>{const preference=new PreferenceEngine().update([], [memory()], new Date(now).toISOString())[0];const recommendations=new RecommendationEngine().generate(context,[memory()],[preference],[],new Date(now).toISOString());assert.ok(recommendations.some(item=>item.reason.includes('sessions')));assert.ok(recommendations.every(item=>!item.reason.includes('window title')))});
test('personalization summary separates rising and declining interests',()=>{const e=new PreferenceEngine();const prefs=e.update([], [memory()],new Date(now).toISOString());const summary=buildPersonalizationSummary(prefs,{...emptyFeedbackSummary(),byTopic:{Godot:{useful:2,not_useful:0,dismissed:0,ignored:0}}});assert.ok(summary.topInterests.length);assert.ok(summary.feedbackPatterns.some(x=>x.name==='Godot'))});
