const test = require('node:test');
const assert = require('node:assert/strict');
const { validateGoalInput, deriveGoal } = require('../dist/goal-engine');
const { validatePlanProposal } = require('../dist/plan-engine');
const { AGENT_TOOLS } = require('../dist/agent-tools');
test('goal input is bounded and explicit progress is distinguished', () => { const goal = validateGoalInput({ title: ' Finish my Godot game ', description: 'x'.repeat(2000), priority: 99, progress: .4, progressSource: 'explicit', associations: { projects: ['Football'], technologies: ['Godot'] } }); assert.equal(goal.title, 'Finish my Godot game'); assert.equal(goal.description.length, 1000); assert.equal(goal.priority, 5); assert.equal(goal.explicitProgress, .4); });
test('derived goal progress uses structured evidence only', () => { const input=validateGoalInput({title:'Godot game',associations:{projects:['Football'],technologies:['Godot']}}); const goal={id:'goal:1',title:input.title,description:input.description,category:input.category,status:'active',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',priority:3,progress:0,progressSource:'derived',associations:input.associations,activeDays:0,trend:'stable'}; const result=deriveGoal(goal,[{id:'m',type:'topic',name:'Godot',category:'Programming',strength:.7,confidence:.8,firstSeen:'2026-01-01',lastSeen:'2026-10-01T00:00:00Z',evidenceCount:3,totalSeconds:100,source:'context',metadataJson:'{}'}],[],[],Date.parse('2026-10-02T00:00:00Z')); assert.ok(result.progress>0); assert.equal(result.progressSource,'derived'); });
test('agent plan validation rejects unknown and malformed tools', () => { assert.throws(()=>validatePlanProposal({title:'bad',steps:[{tool:'execute_command',arguments:{}}]},AGENT_TOOLS)); assert.throws(()=>validatePlanProposal({title:'bad',steps:[{tool:'open_url',arguments:{url:'https://x',extra:'no'}}]},AGENT_TOOLS)); });
test('agent plan validation bounds safe level two steps', () => { const plan=validatePlanProposal({title:'Open docs',description:'safe',steps:[{title:'Open URL',tool:'open_url',arguments:{url:'https://developer.example'}}]},AGENT_TOOLS,'2026-10-02T00:00:00Z'); assert.equal(plan.status,'pending_confirmation'); assert.equal(plan.steps[0].permissionLevel,2); assert.equal(plan.steps[0].requiresConfirmation,true); assert.equal(plan.steps[0].arguments.url,'https://developer.example'); });
