const test=require('node:test');const assert=require('node:assert/strict');const {DeterministicLocalEmbeddingProvider,LocalNeuralEmbeddingProvider,UnavailableEmbeddingProvider}=require('../dist/embedding-provider');const {SemanticMemoryEngine,cosineSimilarity}=require('../dist/semantic-memory-engine');
const memory=(id,name,category='Game Development',strength=.7,lastSeen='2026-09-30T12:00:00.000Z')=>({id,type:'topic',name,category,strength,confidence:.8,firstSeen:lastSeen,lastSeen,evidenceCount:3,totalSeconds:100,source:'test',metadataJson:JSON.stringify({topic:name,technologies:['Godot']})});
function store(){const map=new Map();return {getEmbedding:id=>map.get(id)||null,saveEmbedding:x=>map.set(x.memoryId,x),getEmbeddings:()=>[...map.values()],deleteEmbedding:id=>map.delete(id),clearEmbeddings:()=>map.clear(),map};}
test('local provider is deterministic and batched',async()=>{const p=new DeterministicLocalEmbeddingProvider();const a=await p.embed('Godot navigation');const b=await p.embed('Godot navigation');assert.equal(a.length,p.dimensions);assert.deepEqual(a,b);assert.deepEqual(await p.embedBatch(['Godot navigation']),[a]);assert.equal(p.isAvailable(),true)});
test('unavailable provider degrades safely',async()=>{const p=new UnavailableEmbeddingProvider();assert.equal(p.isAvailable(),false);assert.deepEqual(await p.embed('x'),[]);});
test('neural provider validates a safe descriptor and uses a mocked local runtime',async()=>{const runtime={isAvailable:()=>true,dimensions:3,embed:async text=>text? [1,0,0]:[],embedBatch:async texts=>texts.map(text=>text?[1,0,0]:[])};const descriptor={modelId:'mini-local',modelName:'Mock Neural',format:'private-context-neural-manifest-v1',dimensions:3};const p=new LocalNeuralEmbeddingProvider(descriptor,runtime);assert.equal(p.isAvailable(),true);assert.equal(p.dimensions,3);assert.deepEqual(await p.embed('structured topic'),[1,0,0]);assert.deepEqual(await p.embedBatch(['x']),[[1,0,0]]);});
test('neural provider rejects missing or invalid models without fallback network',async()=>{const p=new LocalNeuralEmbeddingProvider(null);assert.equal(p.isAvailable(),false);assert.deepEqual(await p.embed('x'),[]);const invalid=new LocalNeuralEmbeddingProvider({modelId:'../escape',modelName:'bad',format:'private-context-neural-manifest-v1',dimensions:3},{isAvailable:()=>true,dimensions:3,embed:async()=>[1,0,0],embedBatch:async()=>[[1,0,0]]});assert.equal(invalid.isAvailable(),false)});
test('cosine handles identical, orthogonal, opposite, zero, and mismatch vectors',()=>{assert.equal(cosineSimilarity([1,0],[1,0]),1);assert.equal(cosineSimilarity([1,0],[0,1]),0);assert.equal(cosineSimilarity([1,0],[-1,0]),-1);assert.equal(cosineSimilarity([0,0],[1,0]),0);assert.equal(cosineSimilarity([1],[1,0]),0)});
test('embedding text contains structured fields only',()=>{const e=new SemanticMemoryEngine(new DeterministicLocalEmbeddingProvider());const text=e.embeddingText(memory('m','enemy pathfinding'));assert.ok(text.includes('Category: Game Development'));assert.ok(text.includes('Topic: enemy pathfinding'));assert.ok(text.includes('Technologies: Godot'));assert.ok(!text.includes('/users'));});
test('indexing skips unchanged text and replaces changed text',async()=>{const s=store();const e=new SemanticMemoryEngine(new DeterministicLocalEmbeddingProvider(),s);const m=memory('m','Godot navigation');const first=await e.indexMemory(m);const second=await e.indexMemory(m);assert.equal(first.createdAt,second.createdAt);assert.equal(s.getEmbeddings().length,1);const changed={...m,name:'enemy pathfinding'};const third=await e.indexMemory(changed);assert.notEqual(third.textHash,first.textHash);assert.equal(s.getEmbeddings().length,1)});
test('semantic retrieval sorts deterministically and respects threshold and limit',async()=>{const s=store();const e=new SemanticMemoryEngine(new DeterministicLocalEmbeddingProvider(),s);const memories=[memory('a','Godot navigation', 'Game Development',.8),memory('b','music mixing','Music',.9),memory('c','enemy pathfinding','Game Development',.7)];await e.indexMemories(memories,10);const results=await e.searchSimilarMemories('Godot navigation',memories,2,.1);assert.ok(results.length<=2);assert.equal(results[0].memory.id,'a');assert.ok(results.every(x=>x.similarity>=.1&&x.similarity<=1));});
test('provider and model changes replace incompatible vectors incrementally',async()=>{const s=store();const m=memory('m','Godot');const deterministic=new SemanticMemoryEngine(new DeterministicLocalEmbeddingProvider(),s);await deterministic.indexMemory(m);const neural=new LocalNeuralEmbeddingProvider({modelId:'mini',modelName:'Mock',format:'private-context-neural-manifest-v1',dimensions:3},{isAvailable:()=>true,dimensions:3,embed:async()=>[1,0,0],embedBatch:async()=>[[1,0,0]]});const neuralEngine=new SemanticMemoryEngine(neural,s);assert.deepEqual(await neuralEngine.searchSimilarMemories('Godot',[m],10,0),[]);await neuralEngine.indexMemories([m],1);assert.equal(s.getEmbeddings()[0].provider,'local-neural');assert.equal((await neuralEngine.searchSimilarMemories('Godot',[m],10,0))[0].memory.id,'m')});
test('delete and clear remove vectors',async()=>{const s=store();const e=new SemanticMemoryEngine(new DeterministicLocalEmbeddingProvider(),s);const m=memory('m','Godot');await e.indexMemory(m);e.removeMemory(m.id);assert.equal(s.getEmbeddings().length,0);await e.indexMemory(m);e.clear();assert.equal(s.getEmbeddings().length,0)});
