import { app, BrowserWindow, dialog, ipcMain } from 'electron';
import fs from 'node:fs';
import path from 'node:path';
import { randomUUID, createHash } from 'node:crypto';
import { ActivityDatabase } from './database';
import { PrivacyManager } from './privacy-manager';
import { ActivityCollector } from './activity-collector';
import { ContextEngine } from '../context-engine';
import { MemoryEngine } from '../memory-engine';
import { PreferenceEngine } from '../preference-engine';
import { RecommendationEngine } from '../recommendation-engine';
import { AgentEngine } from '../agent-engine';
import { AGENT_TOOLS } from '../agent-tools';
import { ExternalLLMProvider } from '../llm-provider';
import { PermissionManager } from './permission-manager';
import { ActionExecutor } from './action-executor';
import { normalizeFeedback } from '../feedback-engine';
import { buildPersonalizationSummary } from '../personalization-engine';
import { MemoryRecord } from '../shared/contracts';
import { normalizeDomainRules, validateBrowserPayload } from '../browser-context';
import { isSensitiveFilename, scanSelectedFolder } from '../folder-context';
import { Diagnostics } from './diagnostics';
import { TaskManager } from './task-manager';
import { DeterministicLocalEmbeddingProvider, LocalNeuralEmbeddingProvider, LocalNeuralModelDescriptor, validLocalNeuralDescriptor } from '../embedding-provider';
import { SemanticMemoryEngine, SimilarMemory } from '../semantic-memory-engine';
import { BrowserConnectorServer } from './browser-connector';
import { explainAction, explainContext, explainMemory, explainPreference, explainRecommendation, explainSemantic } from '../explainability';
import { buildConceptCluster } from '../memory-clusters';
import { buildProjectProfiles } from '../project-intelligence';
import { deriveGoal, validateGoalInput } from '../goal-engine';
import { validatePlanProposal } from '../plan-engine';
import { AgentPlan, Goal, GoalMilestone } from '../shared/contracts';

let db: ActivityDatabase; let privacy: PrivacyManager; let collector: ActivityCollector; let permissions: PermissionManager; let actionExecutor: ActionExecutor; let semanticMemory: SemanticMemoryEngine; let diagnostics: Diagnostics; let tasks: TaskManager; let connector: BrowserConnectorServer; let shuttingDown = false;
function parseConfiguredList<T>(key: string): T[] { try { const raw = process.env[key]; const parsed = raw ? JSON.parse(raw) : []; return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function installedNeuralDescriptor(modelId: string): LocalNeuralModelDescriptor | null { if (!/^[A-Za-z0-9._-]{1,80}$/.test(modelId)) return null; const root = path.resolve(app.getPath('userData'), 'models'); const directory = path.resolve(root, modelId); if (directory !== path.join(root, modelId)) return null; try { const descriptor = JSON.parse(fs.readFileSync(path.join(directory, 'model.json'), 'utf8')) as unknown; if (!validLocalNeuralDescriptor(descriptor) || descriptor.modelId !== modelId) return null; return descriptor; } catch { return null; } }
function localNeuralModels() { const root = path.resolve(app.getPath('userData'), 'models'); try { return fs.readdirSync(root, { withFileTypes: true }).filter(item => item.isDirectory()).map(item => installedNeuralDescriptor(item.name)).filter((item): item is LocalNeuralModelDescriptor => Boolean(item)).map(item => { const provider = new LocalNeuralEmbeddingProvider(item); const active = db.setting('embeddingProvider','local-deterministic') === 'local-neural' && db.setting('localNeuralModel','') === item.modelId; return { modelId: item.modelId, modelName: item.modelName, dimensions: item.dimensions, available: provider.isAvailable(), status: active && provider.isAvailable() ? 'active' as const : provider.isAvailable() ? 'valid' as const : 'unavailable' as const }; }); } catch { return []; } }
function configureSemanticMemory() { const provider = db.setting('embeddingProvider', 'local-deterministic'); const modelId = db.setting('localNeuralModel', ''); if (provider === 'local-neural') { const neural = new LocalNeuralEmbeddingProvider(installedNeuralDescriptor(modelId)); semanticMemory = neural.isAvailable() ? new SemanticMemoryEngine(neural, db) : new SemanticMemoryEngine(new DeterministicLocalEmbeddingProvider(), db); } else semanticMemory = new SemanticMemoryEngine(new DeterministicLocalEmbeddingProvider(), db); }
let lastFolderScanAt = 0; let importCandidate: unknown = null;
function browserRules() { try { return normalizeDomainRules({ allowed: JSON.parse(db.setting('browserAllowedDomains', '[]')), blocked: JSON.parse(db.setting('browserBlockedDomains', '[]')) }); } catch { return { allowed: [], blocked: [] }; } }
function browserStatus() { const recent = db.recentBrowserContext(20); const enabled = db.setting('browserContextEnabled', 'false') === 'true'; const connectionState = connector?.connectionState(enabled) ?? (enabled ? 'not_paired' : 'disabled'); const rules = browserRules(); return { enabled, connected: connectionState === 'connected', connectionState, pendingPairing: connector?.pendingRequests ?? [], allowedDomains: rules.allowed, blockedDomains: rules.blocked, recent }; }
function folderStatus() { const folders = db.selectedFolderSummaries(); return { enabled: db.setting('folderTrackingEnabled', 'false') === 'true', folders, totalFiles: db.folderFileCount() }; }
async function scanFoldersIfDue(force = false) { if (db.setting('folderTrackingEnabled', 'false') !== 'true' || !privacy.isTrackingAllowed()) return; if (!force && Date.now() - lastFolderScanAt < 30000) return; lastFolderScanAt = Date.now(); const fsAdapter = { list: async (directory: string) => { const entries = await fs.promises.readdir(directory, { withFileTypes: true }); return Promise.all(entries.map(async entry => { const full = path.join(directory, entry.name); if (entry.isDirectory()) return { name: entry.name, isDirectory: true, size: 0, modifiedAt: new Date().toISOString() }; const stat = await fs.promises.stat(full); return { name: entry.name, isDirectory: false, size: stat.size, modifiedAt: stat.mtime.toISOString() }; })); } }; for (const folder of db.selectedFolders().filter(item => item.enabled)) { try { const entries = await scanSelectedFolder(folder, fsAdapter, { maxFiles: 500, maxDepth: 5 }); db.saveFolderEntries(folder.id, entries, new Date().toISOString()); } catch { diagnostics?.record('folder_scan', 'error', 'scan_failed'); } } }
const contextEngine = new ContextEngine(); const memoryEngine = new MemoryEngine(); const preferenceEngine = new PreferenceEngine(); const recommendationEngine = new RecommendationEngine(); const agentEngine = new AgentEngine(); const llmProvider = new ExternalLLMProvider();
let lastContextKey = ''; let lastMemoryMarker = ''; let lastMemoryActivityId = ''; let lastMemoryDuration = 0; let lastRecommendationMarker = ''; let lastLLMMarker = ''; let cachedAgentResponses = [] as import('../shared/contracts').AgentResponse[];

function derivedGoals() { return db.goals().map(goal => ({...deriveGoal(goal, db.memories(), db.preferences(), buildProjectProfiles(db.memories(), Date.now(), 50)), milestones: db.milestones(goal.id)})); }
async function contextAndMemory() {
  const current = collector.currentActivity(); const browserItems = db.setting('browserContextEnabled', 'false') === 'true' ? db.browserActivities(30) : []; const folderItems = db.setting('folderTrackingEnabled', 'false') === 'true' ? db.folderActivities(60) : []; const recent = [...db.recent(60), ...browserItems, ...folderItems].sort((a, b) => Date.parse(b.startedAt) - Date.parse(a.startedAt)).slice(0, 100); const context = contextEngine.build(current ? [current, ...recent] : recent);
  const contextKey = context ? JSON.stringify([context.category, context.parentCategory, context.topic, context.subtopic, context.project, context.recentTopics, context.sourceTypes, context.sessionId, context.transitions]) : '';
  if (context && privacy.isTrackingAllowed() && contextKey !== lastContextKey) { db.recordContext(context); lastContextKey = contextKey; }
  const learningEnabled = db.setting('memoryLearning', 'true') === 'true'; let meaningfulObservation = false; let changedMemories: MemoryRecord[] | null = null;
  if (context && learningEnabled && privacy.isTrackingAllowed()) {
    const minuteBucket = current ? Math.floor(current.durationSeconds / 60) : 0; const marker = `${current?.id ?? context.sessionId ?? 'history'}:${context.topic ?? context.category}:${context.project ?? ''}:${minuteBucket}`;
    if (marker !== lastMemoryMarker) {
      const previousDuration = current?.id === lastMemoryActivityId ? lastMemoryDuration : 0; const durationSeconds = current ? Math.max(1, current.durationSeconds - previousDuration) : Math.max(1, context.evidenceDurationSeconds ?? recent.reduce((sum, item) => sum + item.durationSeconds, 0));
      changedMemories = memoryEngine.update(db.memories(), { context, observedAt: new Date().toISOString(), durationSeconds, sessionId: context.sessionId }); for (const memory of changedMemories) db.upsertMemory(memory);
      db.cleanupMemory(); lastMemoryMarker = marker; lastMemoryActivityId = current?.id ?? ''; lastMemoryDuration = current?.durationSeconds ?? 0; meaningfulObservation = true;
    }
  }
  let semanticMatches: SimilarMemory[] = []; const semanticEnabled = db.setting('semanticMemoryEnabled', 'true') === 'true';
  if (semanticEnabled && semanticMemory.isAvailable() && context && privacy.isTrackingAllowed()) { const memories = db.memories(); await semanticMemory.indexMemories(memories, 3); semanticMatches = await semanticMemory.searchSimilarMemories([context.category, context.topic, context.subtopic, context.project, ...context.technologies].filter(Boolean).join(' '), memories, 8, 0.15); }
  if (changedMemories) { const support = Object.fromEntries(semanticMatches.map(item => [item.memory.name, item.similarity])); const preferences = preferenceEngine.update(db.preferences(), changedMemories, new Date().toISOString(), db.getFeedbackSummary(), support); for (const preference of preferences) db.upsertPreference(preference); }
  if (context && privacy.isTrackingAllowed() && db.setting('recommendationsEnabled','true') === 'true' && db.setting('recommendationFrequency','normal') !== 'off' && (meaningfulObservation || contextKey !== lastRecommendationMarker)) { const semanticRelevance = semanticMatches.length ? semanticMatches[0].similarity : 0; const recommendations = recommendationEngine.generate(context, db.memories(), db.preferences(), recent, db.getFeedbackSummary(), new Date().toISOString(), semanticRelevance, derivedGoals()); for (const recommendation of recommendations) db.saveRecommendation(recommendation); db.deleteOldRecommendations(); lastRecommendationMarker = contextKey; }
  return { context, current, recent, semanticMatches };
}

function memoryState() {
  const memories = db.memories();
  return { learningEnabled: db.setting('memoryLearning','true') === 'true', retention: db.setting('memoryRetention','90 days'), memories, topPreferences: preferenceEngine.getTopPreferences(db.preferences(), 8), recentMemories: memoryEngine.getRecentMemories(memories, new Date(Date.now() - 7 * 86400000).toISOString()).slice(0, 8) };
}
function ensureOperational() { if (shuttingDown || !db) throw new Error('application_shutting_down'); }
async function state() {
  ensureOperational(); const p = privacy.snapshot(); const result = await contextAndMemory();
  const recommendations = db.getRecentRecommendations(8); const memories = db.memories(); const preferences = db.preferences(); const personalization = buildPersonalizationSummary(preferences, db.getFeedbackSummary());
  const semanticOrdered = [...result.semanticMatches.map(item => item.memory), ...memories.filter(memory => !result.semanticMatches.some(item => item.memory.id === memory.id))];
  const deterministic = agentEngine.generate(result.context, semanticOrdered, preferences, recommendations, AGENT_TOOLS);
  const agentMarker = JSON.stringify([lastContextKey, recommendations.map(r => r.id)]);
  const aiEnabled = db.setting('aiEnabled','false') === 'true';
  if (aiEnabled && result.context && agentMarker !== lastLLMMarker) {
    cachedAgentResponses = await agentEngine.generateWithLLM(result.context, semanticOrdered, preferences, recommendations, AGENT_TOOLS, llmProvider, new Date().toISOString(), reason => db.audit('llm_validation_or_provider_failure', reason), db.getFeedbackSummary());
    const now = new Date();
    for (const response of cachedAgentResponses) if (response.action) { const checked = permissions.validateAction(response.action); if (checked.ok) { const expiresAt = new Date(now.getTime() + 5 * 60 * 1000).toISOString(); db.savePendingAgentAction({ id: response.action.id ?? `agent-action:${response.id}`, toolName: response.action.toolName, request: { ...response.action, id: response.action.id ?? `agent-action:${response.id}`, status: 'pending', createdAt: now.toISOString(), expiresAt }, status: 'pending', createdAt: now.toISOString(), expiresAt, sourceContext: response.sourceContext, reason: response.explanation }); db.audit('action_requested', `${response.action.id ?? response.id}:${response.action.toolName}`); } else db.audit('action_validation_failed', `${response.id}:${checked.reason}`); }
    lastLLMMarker = agentMarker;
  } else if (!aiEnabled) { cachedAgentResponses = deterministic; lastLLMMarker = ''; }
  return { tracking: privacy.isTrackingAllowed(), pauseMode: p.mode, pausedUntil: p.pausedUntil, platform: process.platform, collectorAvailable: collector.available, current: result.current, recent: db.recent(), applicationsTracked: db.countApps(), retention: db.setting('retention','30 days'), titleCollection: db.setting('titleCollection','true') === 'true', exclusions: db.excludedApps(), context: result.context, memory: memoryState(), recommendations, feedbackSummary: db.getFeedbackSummary(), personalization, semanticMemory: { ...semanticMemory.status(), enabled: db.setting('semanticMemoryEnabled', 'true') === 'true', selectedModel: db.setting('localNeuralModel', '') }, browserContext: browserStatus(), folderContext: folderStatus(), agentResponses: cachedAgentResponses, pendingAgentActions: db.getPendingAgentActions() };
}
function aiStatus() { const enabled = db.setting('aiEnabled','false') === 'true'; const configured = llmProvider.isConfigured(); return { enabled, configured, provider: db.setting('aiProvider','external'), status: !enabled ? 'disabled' : configured ? 'configured' : 'not_configured' }; }
async function processRetryableWorkflows() { if (!privacy?.isTrackingAllowed() || !actionExecutor) return; let processed=0; for (const plan of db.plans()) { if(processed>=3) break; const step=plan.steps.find(item=>item.status==='failed'&&item.retryable&&item.nextRetryAt&&Date.parse(item.nextRetryAt)<=Date.now()&&(item.attemptCount??0)<(item.maxAttempts??1)); if(!step) continue; step.status='approved'; db.savePlan({...plan,status:'approved',steps:plan.steps}); processed++; const action={id:`plan-action:${step.id}`,toolName:step.tool,request:{id:`plan-action:${step.id}`,toolName:step.tool,arguments:step.arguments,permissionLevel:2,requiresConfirmation:true,status:'approved' as const,sourceContext:plan.sourceContext,reason:'Bounded retry'},status:'approved' as const,createdAt:step.createdAt,expiresAt:plan.expiresAt,sourceContext:plan.sourceContext,reason:'Bounded retry'}; db.savePendingAgentAction(action); await actionExecutor.execute(action); } }
function createWindow() { const win = new BrowserWindow({ width: 1180, height: 900, minWidth: 900, minHeight: 700, webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true } }); win.loadFile(path.join(__dirname, '../renderer/index.html')); }

app.whenReady().then(async () => {
  diagnostics = new Diagnostics(); db = new ActivityDatabase(); db.cleanup(); db.cleanupMemory(); connector = new BrowserConnectorServer({ loadTokenHash: () => db.browserPairingTokenHash(), saveTokenHash: hash => db.saveBrowserPairingTokenHash(hash), clearTokenHash: () => db.clearBrowserPairingTokenHash(), acceptPayload: payload => { if (db.setting('browserContextEnabled', 'false') !== 'true' || !privacy.isTrackingAllowed()) return { accepted: false }; const record = validateBrowserPayload(payload, browserRules()); if (!record) return { accepted: false }; db.saveBrowserContext(record); db.audit('browser_context_ingested', record.domain); return { accepted: true }; } }); configureSemanticMemory(); permissions = new PermissionManager(AGENT_TOOLS, { applications: parseConfiguredList('APPROVED_APPLICATIONS_JSON'), folders: parseConfiguredList('APPROVED_FOLDERS_JSON') }); actionExecutor = new ActionExecutor(permissions, db); privacy = new PrivacyManager(db); try { await connector.start(); } catch { diagnostics.record('browser_connector', 'error', 'connector_unavailable'); } collector = new ActivityCollector(db, privacy); collector.start(); tasks = new TaskManager((component, code) => diagnostics.record(component, 'error', code)); tasks.register('maintenance', 60000, async () => { db.cleanup(); db.cleanupMemory(); await scanFoldersIfDue(true); }); tasks.register('workflow-retry', 5000, processRetryableWorkflows); tasks.startAll();
  ipcMain.handle('app-info', () => ({ name: app.getName(), version: app.getVersion(), phase: 'Phase 24 — Final Release Validation', privacy: 'local-first' as const, neuralProvider: semanticMemory?.status().provider ?? 'unavailable' }));
  ipcMain.handle('state', () => state());
  ipcMain.handle('get-context-explanation', async () => { ensureOperational(); const result = await contextAndMemory(); return result.context ? explainContext(result.context) : null; });
  const derivedGoals = () => db.goals().map(goal => deriveGoal(goal, db.memories(), db.preferences(), buildProjectProfiles(db.memories(), Date.now(), 50)));
  const goalId = (value: unknown) => { if(typeof value!=='string'||!/^[A-Za-z0-9:_-]{1,120}$/.test(value)) throw new Error('Invalid goal id'); return value; };
  ipcMain.handle('get-goals', () => { ensureOperational(); return derivedGoals(); });
  ipcMain.handle('get-goal-details', (_e,id:unknown) => { ensureOperational(); return derivedGoals().find(g=>g.id===goalId(id))??null; });
  ipcMain.handle('create-goal', (_e,input:unknown) => { ensureOperational(); const data=validateGoalInput(input); const now=new Date().toISOString(); const goal:Goal={id:`goal:${randomUUID()}`,title:data.title,description:data.description,category:data.category,status:data.status,createdAt:now,updatedAt:now,targetDate:data.targetDate,priority:data.priority,progress:data.explicitProgress??0,progressSource:data.explicitProgress===undefined?'derived':'explicit',associations:data.associations,activeDays:0,trend:'stable'}; db.saveGoal(goal); db.audit('goal_created',goal.id); return goal; });
  ipcMain.handle('update-goal', (_e,id:unknown,input:unknown) => { ensureOperational(); const old=db.goal(goalId(id)); if(!old) throw new Error('Unknown goal'); const data=validateGoalInput({...old,...(input&&typeof input==='object'?input:{})}); const updated={...old,...data,updatedAt:new Date().toISOString(),progress:data.explicitProgress??old.progress,progressSource:data.explicitProgress===undefined?old.progressSource:'explicit'} as Goal; db.saveGoal(updated); return deriveGoal(updated,db.memories(),db.preferences(),buildProjectProfiles(db.memories(),Date.now(),50)); });
  const setGoalStatus=(status:Goal['status'])=> (_e:unknown,id:unknown)=>{ensureOperational();const old=db.goal(goalId(id));if(!old)throw new Error('Unknown goal');const updated={...old,status,updatedAt:new Date().toISOString()} as Goal;db.saveGoal(updated);db.audit(`goal_${status}`,updated.id);return updated;};
  ipcMain.handle('pause-goal',setGoalStatus('paused')); ipcMain.handle('resume-goal',setGoalStatus('active')); ipcMain.handle('complete-goal',setGoalStatus('completed')); ipcMain.handle('archive-goal',setGoalStatus('archived'));
  ipcMain.handle('delete-goal',(_e,id:unknown)=>{ensureOperational();db.deleteGoal(goalId(id));return undefined;});
  const milestoneId=(value:unknown)=>{if(typeof value!=='string'||!/^[A-Za-z0-9:_-]{1,140}$/.test(value))throw new Error('Invalid milestone id');return value;};
  ipcMain.handle('create-milestone',(_e,goalValue:unknown,input:unknown)=>{ensureOperational();const gid=goalId(goalValue);if(!db.goal(gid))throw new Error('Unknown goal');const x=input&&typeof input==='object'?input as Record<string,unknown>:{};const title=typeof x.title==='string'?x.title.trim().slice(0,160):'';if(!title)throw new Error('Milestone title is required');const now=new Date().toISOString();const milestone:GoalMilestone={id:`milestone:${randomUUID()}`,goalId:gid,title,description:typeof x.description==='string'?x.description.slice(0,500):'',status:'active',createdAt:now,updatedAt:now};db.saveMilestone(milestone);return milestone;});
  ipcMain.handle('update-milestone',(_e,id:unknown,input:unknown)=>{ensureOperational();const mid=milestoneId(id);const raw=input&&typeof input==='object'?input as Record<string,unknown>:{};const found=db.milestone(mid); if(!found) throw new Error('Unknown milestone'); const updated={...found,title:typeof raw.title==='string'?raw.title.slice(0,160):found.title,description:typeof raw.description==='string'?raw.description.slice(0,500):found.description,updatedAt:new Date().toISOString()};db.saveMilestone(updated);return updated;});
  ipcMain.handle('complete-milestone',(_e,id:unknown)=>{ensureOperational();const mid=milestoneId(id);const found=db.milestone(mid);if(!found)throw new Error('Unknown milestone');const updated={...found,status:'completed' as const,updatedAt:new Date().toISOString()};db.saveMilestone(updated);return updated;});
  ipcMain.handle('delete-milestone',(_e,id:unknown)=>{ensureOperational();db.deleteMilestone(milestoneId(id));return undefined;});
  const validateSnapshot=(value:unknown)=>{if(!value||typeof value!=='object')throw new Error('Invalid import');const x=value as Record<string,unknown>;if(x.schemaVersion!==17||!Array.isArray(x.goals)||!Array.isArray(x.memories)||!Array.isArray(x.preferences)||!Array.isArray(x.recommendations)||!Array.isArray(x.feedback)||!Array.isArray(x.plans)||x.goals.length>100||x.memories.length>1000||x.preferences.length>500||x.recommendations.length>100||x.feedback.length>1000||x.plans.length>50)throw new Error('Unsupported import schema');if(typeof x.checksum==='string'){const copy={...x};delete copy.checksum;if(createHash('sha256').update(JSON.stringify(copy)).digest('hex')!==x.checksum)throw new Error('Backup checksum mismatch');}return x;};
  ipcMain.handle('export-data',async()=>{ensureOperational();const result=await dialog.showSaveDialog({defaultPath:'private-context-export.json',filters:[{name:'JSON',extensions:['json']}]});if(result.canceled||!result.filePath)return {ok:false};const snapshot=db.exportSnapshot();fs.writeFileSync(result.filePath,JSON.stringify(snapshot,null,2),'utf8');db.audit('data_exported',String(snapshot.goals.length));return {ok:true,file:'private-context-export.json',counts:{goals:snapshot.goals.length,memories:snapshot.memories.length,plans:snapshot.plans.length}};});
  ipcMain.handle('preview-import',async()=>{ensureOperational();const result=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'JSON',extensions:['json']}]});if(result.canceled||!result.filePaths[0])return {ok:false};try{const parsed=validateSnapshot(JSON.parse(fs.readFileSync(result.filePaths[0],'utf8')));importCandidate=parsed;return {ok:true,counts:{goals:(parsed.goals as unknown[]).length}};}catch(error){importCandidate=null;return {ok:false,error:error instanceof Error?error.message:'Invalid import'};}});
  ipcMain.handle('import-data',()=>{ensureOperational();if(!importCandidate)return {ok:false,error:'Run import preview first'};const parsed=validateSnapshot(importCandidate);const goals=parsed.goals as unknown[];for(const item of goals){const data=validateGoalInput(item);const source=item as Record<string,unknown>;const id=typeof source.id==='string'?source.id:'';if(!/^goal:[A-Za-z0-9-]{20,80}$/.test(id)||db.goal(id))throw new Error('Goal id conflicts with existing data');const target=item as Record<string,unknown>;Object.assign(target,{id, title:data.title,description:data.description,category:data.category,status:data.status,createdAt:typeof source.createdAt==='string'?source.createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),targetDate:data.targetDate,priority:data.priority,progress:data.explicitProgress??0,progressSource:data.explicitProgress===undefined?'derived':'explicit',associations:data.associations,activeDays:0,trend:'stable'});}for(const plan of parsed.plans as unknown[]){const p=plan as Record<string,unknown>;if(typeof p.id!=='string'||!/^plan:[A-Za-z0-9-]{20,80}$/.test(p.id)||db.plan(p.id)||!Array.isArray(p.steps)||p.steps.length>10)throw new Error('Plan conflict or invalid steps');const ids=new Set((p.steps as unknown[]).map(s=>typeof (s as any)?.id==='string'?(s as any).id:''));for(const step of p.steps as unknown[]){const deps=Array.isArray((step as any).dependsOn)?(step as any).dependsOn:[];if(deps.length>10||deps.some((d:string)=>!ids.has(d)))throw new Error('Invalid plan dependency');}}db.importPortableData(parsed);importCandidate=null;db.audit('data_imported',String(goals.length));return {ok:true,counts:{goals:goals.length,memories:(parsed.memories as unknown[]).length,preferences:(parsed.preferences as unknown[]).length,recommendations:(parsed.recommendations as unknown[]).length,plans:(parsed.plans as unknown[]).length}};});
  ipcMain.handle('backup-data',async()=>{ensureOperational();const result=await dialog.showSaveDialog({defaultPath:'private-context-backup.json',filters:[{name:'JSON',extensions:['json']}]});if(result.canceled||!result.filePath)return {ok:false};const snapshot=db.exportSnapshot();fs.writeFileSync(result.filePath,JSON.stringify({backupVersion:1,snapshot},null,2),'utf8');return {ok:true,file:'private-context-backup.json'};});
  ipcMain.handle('get-data-lifecycle',()=>{ensureOperational();return db.dataLifecycle();});
  ipcMain.handle('get-agent-plans',()=>{ensureOperational();return db.plans();}); ipcMain.handle('get-agent-plan-details',(_e,id:unknown)=>{ensureOperational();if(typeof id!=='string')throw new Error('Invalid plan id');return db.plan(id);});
  ipcMain.handle('create-agent-plan',(_e,input:unknown)=>{ensureOperational();const plan=validatePlanProposal(input,permissions.getTools());if(plan.goalId&&!db.goal(plan.goalId))throw new Error('Unknown goal');db.savePlan(plan);return plan;});
  const planStatus=(status:string)=>(_e:unknown,id:unknown)=>{ensureOperational();if(typeof id!=='string')throw new Error('Invalid plan id');const plan=db.plan(id);if(!plan)throw new Error('Unknown plan');if(status==='approved'&&plan.steps.some(s=>s.status!=='pending'&&s.status!=='approved'))throw new Error('Invalid step state');const updated={...plan,status:status as AgentPlan['status'],steps:status==='approved'?plan.steps.map(s=>({...s,status:'approved' as const})):plan.steps};db.savePlan(updated);return updated;};
  ipcMain.handle('approve-agent-plan',planStatus('approved')); ipcMain.handle('approve-agent-plan-step',(_e,planId:unknown,stepId:unknown)=>{ensureOperational();if(typeof planId!=='string'||typeof stepId!=='string')throw new Error('Invalid step request');const plan=db.plan(planId);if(!plan)throw new Error('Unknown plan');const step=plan.steps.find(s=>s.id===stepId);if(!step||step.status!=='pending')throw new Error('Step is not pending');step.status='approved';const status=plan.steps.every(s=>s.status==='approved'||s.status==='completed')?'approved':'pending_confirmation';db.savePlan({...plan,status,steps:plan.steps});db.audit('step_approved',step.id);return db.plan(planId);});
  ipcMain.handle('reject-agent-plan-step',(_e,planId:unknown,stepId:unknown)=>{ensureOperational();if(typeof planId!=='string'||typeof stepId!=='string')throw new Error('Invalid step request');const plan=db.plan(planId);if(!plan)throw new Error('Unknown plan');const step=plan.steps.find(s=>s.id===stepId);if(!step||step.status!=='pending')throw new Error('Step is not pending');step.status='rejected';db.savePlan({...plan,status:'pending_confirmation',steps:plan.steps});db.audit('step_rejected',step.id);return db.plan(planId);}); ipcMain.handle('cancel-agent-plan-step',(_e,planId:unknown,stepId:unknown)=>{ensureOperational();if(typeof planId!=='string'||typeof stepId!=='string')throw new Error('Invalid step request');const plan=db.plan(planId);if(!plan)throw new Error('Unknown plan');const step=plan.steps.find(s=>s.id===stepId);if(!step||step.status==='completed'||step.status==='running')throw new Error('Step cannot be cancelled');step.status='cancelled';step.retryable=false;db.savePlan({...plan,status:'paused',steps:plan.steps});db.audit('step_cancelled',step.id);return db.plan(planId);}); ipcMain.handle('reject-agent-plan',planStatus('cancelled')); ipcMain.handle('cancel-agent-plan',planStatus('cancelled'));
  ipcMain.handle('execute-agent-plan',async(_e,id:unknown)=>{ensureOperational();if(typeof id!=='string')throw new Error('Invalid plan id');const plan=db.plan(id);if(!plan||plan.status!=='approved')throw new Error('Plan is not approved');if(Date.now()>=Date.parse(plan.expiresAt)){db.updatePlanStatus(id,'expired');return db.plan(id);};db.updatePlanStatus(id,'running');for(const step of plan.steps){if(step.status!=='approved')continue;if(step.dependsOn?.some(dep=>plan.steps.find(candidate=>candidate.id===dep)?.status!=='completed')){step.status='failed';step.resultSummary='Blocked by failed or incomplete dependency';continue;}step.attemptCount=(step.attemptCount??0)+1;step.lastAttemptAt=new Date().toISOString();const action={id:`plan-action:${step.id}`,toolName:step.tool,request:{id:`plan-action:${step.id}`,toolName:step.tool,arguments:step.arguments,permissionLevel:2,requiresConfirmation:true,status:'approved' as const,sourceContext:plan.sourceContext,reason:step.description},status:'approved' as const,createdAt:step.createdAt,expiresAt:plan.expiresAt,sourceContext:plan.sourceContext,reason:step.description};db.savePendingAgentAction(action);const result=await actionExecutor.execute(action);step.status=result.status==='completed'?'completed':'failed';step.resultSummary=result.status==='completed'?'Action completed safely':(result.error??'Action failed');step.completedAt=new Date().toISOString();step.failureCode=result.status==='completed'?undefined:result.status;step.retryable=result.status==='failed'&&(step.attemptCount??0)<(step.maxAttempts??1);step.nextRetryAt=step.retryable?new Date(Date.now()+Math.min(30000,1000*Math.pow(2,(step.attemptCount??1)-1))).toISOString():undefined;db.savePlan({...plan,status:result.status==='completed'?'running':'failed',steps:plan.steps});if(result.status!=='completed'){db.updatePlanStatus(id,'failed');break;}}const final=db.plan(id);if(final&&final.steps.every(s=>s.status==='completed'))db.updatePlanStatus(id,'completed');return db.plan(id);});
  ipcMain.handle('retry-agent-plan-step',async(_e,planId:unknown,stepId:unknown)=>{ensureOperational();if(typeof planId!=='string'||typeof stepId!=='string')throw new Error('Invalid step request');const plan=db.plan(planId);if(!plan)throw new Error('Unknown plan');const step=plan.steps.find(s=>s.id===stepId);if(!step||step.status!=='failed'||step.retryable===false)throw new Error('Step is not retryable');if((step.attemptCount??0)>=(step.maxAttempts??1))throw new Error('Retry limit reached');step.status='approved';db.savePlan({...plan,status:'approved',steps:plan.steps});return db.plan(planId);});
  ipcMain.handle('get-memory-cluster', (_e, name: unknown, limit?: unknown) => { ensureOperational(); if (typeof name !== 'string' || !name.trim() || name.length > 120) throw new Error('Invalid memory cluster'); const safeLimit = limit === undefined ? 12 : Number(limit); if (!Number.isInteger(safeLimit) || safeLimit < 1 || safeLimit > 20) throw new Error('Invalid cluster limit'); return buildConceptCluster(name, db.memories(), safeLimit, 2); });
  ipcMain.handle('search-memories', (_e, filters: unknown) => { ensureOperational(); if (!filters || typeof filters !== 'object') throw new Error('Invalid memory search'); const raw = filters as Record<string, unknown>; const boundedString = (value: unknown, max: number) => typeof value === 'string' ? value.trim().slice(0, max) : undefined; const number = (value: unknown, min: number, max: number) => value === undefined ? undefined : Number.isFinite(Number(value)) ? Math.max(min, Math.min(max, Number(value))) : undefined; return db.searchMemories({ query: boundedString(raw.query, 200), category: boundedString(raw.category, 100), project: boundedString(raw.project, 120), technology: boundedString(raw.technology, 100), source: boundedString(raw.source, 40), minStrength: number(raw.minStrength, 0, 1), minConfidence: number(raw.minConfidence, 0, 1), recentDays: number(raw.recentDays, 1, 3650), limit: number(raw.limit, 1, 100) }); });
  ipcMain.handle('get-activity-timeline', (_e, filters?: unknown) => { ensureOperational(); const raw = filters && typeof filters === 'object' ? filters as Record<string, unknown> : {}; const limit = typeof raw.limit === 'number' && Number.isInteger(raw.limit) ? Math.max(1, Math.min(200, raw.limit)) : 100; const source = typeof raw.source === 'string' ? raw.source.slice(0, 20) : ''; const activities = db.timelineActivities(limit * 2).filter(item => !source || (item.source ?? 'foreground').includes(source)); const category = typeof raw.category === 'string' ? raw.category.slice(0, 80).toLowerCase() : ''; const project = typeof raw.project === 'string' ? raw.project.slice(0, 120).toLowerCase() : ''; const technology = typeof raw.technology === 'string' ? raw.technology.slice(0, 80).toLowerCase() : ''; return activities.slice(0, limit).map(item => { const context = contextEngine.build([item], Date.parse(item.endedAt ?? item.startedAt) + 1000); return { id: item.id, source: item.source === 'browser' ? 'browser' : item.source === 'folder' ? 'folder' : 'desktop', startedAt: item.startedAt, endedAt: item.endedAt, category: context?.category, topic: context?.topic ?? undefined, project: context?.project ?? undefined, technology: context?.technologies[0], durationSeconds: Math.max(0, Math.min(86400, item.durationSeconds)), confidence: context?.confidence ?? 0, sessionId: context?.sessionId }; }).filter(event => (!category || event.category?.toLowerCase().includes(category)) && (!project || event.project?.toLowerCase().includes(project)) && (!technology || event.technology?.toLowerCase().includes(technology))); });
  ipcMain.handle('get-project-profiles', (_e, limit?: unknown) => { ensureOperational(); const safeLimit = limit === undefined ? 20 : Number(limit); if (!Number.isInteger(safeLimit) || safeLimit < 1 || safeLimit > 50) throw new Error('Invalid project limit'); return buildProjectProfiles(db.memories(), Date.now(), safeLimit); });
  ipcMain.handle('get-local-neural-models', () => { ensureOperational(); return localNeuralModels(); });
  ipcMain.handle('import-local-neural-model', async () => { ensureOperational(); const result = await dialog.showOpenDialog({ properties: ['openDirectory'] }); if (result.canceled || !result.filePaths[0]) return { ok: false }; const selected = path.resolve(result.filePaths[0]); try { const descriptor = JSON.parse(fs.readFileSync(path.join(selected, 'model.json'), 'utf8')) as unknown; if (!validLocalNeuralDescriptor(descriptor)) return { ok: false }; const root = path.resolve(app.getPath('userData'), 'models'); const target = path.join(root, descriptor.modelId); fs.mkdirSync(target, { recursive: true }); fs.copyFileSync(path.join(selected, 'model.json'), path.join(target, 'model.json')); db.audit('local_neural_model_imported', descriptor.modelId); return { ok: true, modelId: descriptor.modelId }; } catch { return { ok: false }; } });
  ipcMain.handle('remove-local-neural-model', (_e, modelId: unknown) => { ensureOperational(); if (typeof modelId !== 'string' || !/^[A-Za-z0-9._-]{1,80}$/.test(modelId)) throw new Error('Invalid model id'); const root = path.resolve(app.getPath('userData'), 'models'); const target = path.resolve(root, modelId); if (target !== path.join(root, modelId)) throw new Error('Invalid model path'); try { fs.rmSync(target, { recursive: true, force: true }); } catch { /* controlled no-op */ } db.audit('local_neural_model_removed', modelId); return undefined; });
  ipcMain.handle('get-privacy-summary', () => { ensureOperational(); return ({ ...db.privacySummary(), tracking: privacy.isTrackingAllowed(), memoryLearning: db.setting('memoryLearning', 'true') === 'true', semanticMemory: db.setting('semanticMemoryEnabled', 'true') === 'true', browserEnabled: db.setting('browserContextEnabled', 'false') === 'true', folderEnabled: db.setting('folderTrackingEnabled', 'false') === 'true' }); });
  ipcMain.handle('get-memory-explanation', (_e, id: unknown) => { ensureOperational(); if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid memory id'); const memory = db.memoryById(id); return memory ? explainMemory(memory) : null; });
  ipcMain.handle('get-preference-explanation', (_e, id: unknown) => { ensureOperational(); if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid preference id'); const preference = db.preferenceById(id); return preference ? explainPreference(preference) : null; });
  ipcMain.handle('get-recommendation-explanation', (_e, id: unknown) => { ensureOperational(); if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid recommendation id'); const recommendation = db.recommendationById(id); return recommendation ? explainRecommendation(recommendation, db.getFeedbackSummary()) : null; });
  ipcMain.handle('get-deletion-impact', (_e, type: unknown, id: unknown) => { ensureOperational(); if (!['memory', 'preference', 'recommendation'].includes(String(type)) || typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid deletion request'); if (type === 'memory') return { willRemove: ['Memory record', 'Semantic embedding', 'Preference with the same learned name, if present'], willKeep: ['Historical desktop activity', 'Browser context', 'Folder metadata', 'Unrelated memories', 'Protected audit records'] }; if (type === 'preference') return { willRemove: ['Preference record'], willKeep: ['Memory evidence', 'Historical activity', 'Semantic embeddings', 'Browser and folder context', 'Protected audit records'] }; return { willRemove: ['Recommendation record', 'Recommendation feedback'], willKeep: ['Memories', 'Preferences', 'Historical activity', 'Browser and folder context', 'Protected audit records'] }; });
  ipcMain.handle('forget-memory', (_e, id: unknown) => { ensureOperational(); if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid memory id'); db.deleteMemory(id); return undefined; });
  ipcMain.handle('clear-semantic-memory', () => { ensureOperational(); db.clearEmbeddings(); db.audit('semantic_memory_cleared'); return undefined; });
  ipcMain.handle('get-semantic-explanation', () => { ensureOperational(); return explainSemantic({ ...semanticMemory.status(), enabled: db.setting('semanticMemoryEnabled', 'true') === 'true', selectedModel: db.setting('localNeuralModel', '') }); });
  ipcMain.handle('get-action-explanation', (_e, id: unknown) => { ensureOperational(); if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid action id'); const action = db.getPendingAgentActions().find(item => item.id === id); return action ? explainAction(action) : null; });
  ipcMain.handle('get-ai-settings', () => ({ enabled: db.setting('aiEnabled','false') === 'true', provider: db.setting('aiProvider','external') }));
  ipcMain.handle('set-ai-enabled', (_e, enabled: boolean) => { if (typeof enabled !== 'boolean') throw new Error('Invalid AI setting'); db.setSetting('aiEnabled', String(enabled)); if (!enabled) lastLLMMarker = ''; return aiStatus(); });
  ipcMain.handle('get-ai-status', () => aiStatus());
  ipcMain.handle('get-semantic-memory-status', () => ({ ...semanticMemory.status(), enabled: db.setting('semanticMemoryEnabled', 'true') === 'true', selectedModel: db.setting('localNeuralModel', '') }));
  ipcMain.handle('get-browser-context-status', () => { ensureOperational(); return browserStatus(); });
  ipcMain.handle('get-browser-pairing-requests', () => { ensureOperational(); return connector.pendingRequests; });
  ipcMain.handle('approve-browser-pairing', (_e, id: unknown) => { ensureOperational(); if (typeof id !== 'string' || !/^[A-Za-z0-9-]{20,50}$/.test(id)) throw new Error('Invalid pairing request'); if (!connector.approve(id)) throw new Error('Unknown pairing request'); return browserStatus(); });
  ipcMain.handle('revoke-browser-pairing', () => { ensureOperational(); connector.revoke(); return browserStatus(); });
  ipcMain.handle('set-browser-context-enabled', (_e, enabled: unknown) => { if (typeof enabled !== 'boolean') throw new Error('Invalid browser setting'); db.setSetting('browserContextEnabled', String(enabled)); return browserStatus(); });
  ipcMain.handle('get-browser-domain-rules', () => browserRules());
  ipcMain.handle('set-browser-domain-rules', (_e, rules: unknown) => { const normalized = normalizeDomainRules(rules); db.setSetting('browserAllowedDomains', JSON.stringify(normalized.allowed)); db.setSetting('browserBlockedDomains', JSON.stringify(normalized.blocked)); db.clearBrowserContext(); db.audit('browser_domain_rules_changed'); return normalized; });
  ipcMain.handle('clear-browser-context', () => { db.clearBrowserContext(); db.audit('browser_context_cleared'); return browserStatus(); });
  ipcMain.handle('ingest-browser-context', (_e, payload: unknown) => { if (db.setting('browserContextEnabled', 'false') !== 'true' || !privacy.isTrackingAllowed()) return { accepted: false }; const record = validateBrowserPayload(payload, browserRules()); if (!record) throw new Error('Invalid browser context payload'); db.saveBrowserContext(record); db.audit('browser_context_ingested', record.domain); return { accepted: true }; });
  ipcMain.handle('get-folder-context-status', () => folderStatus());
  ipcMain.handle('get-diagnostics-status', () => diagnostics.status());
  ipcMain.handle('add-selected-folder', async () => { const result = await dialog.showOpenDialog({ properties: ['openDirectory', 'createDirectory'] }); if (result.canceled || !result.filePaths[0]) return folderStatus(); const selectedPath = path.resolve(result.filePaths[0]); const label = path.basename(selectedPath) || selectedPath; if (isSensitiveFilename(label)) throw new Error('Sensitive folder names cannot be indexed'); const folder = { id: `folder:${randomUUID()}`, label: label.slice(0, 120), path: selectedPath, enabled: true }; db.addSelectedFolder(folder); db.audit('folder_selected', folder.label); await scanFoldersIfDue(true); return folderStatus(); });
  ipcMain.handle('remove-selected-folder', (_e, id: unknown) => { if (typeof id !== 'string' || !/^folder:[A-Za-z0-9-]{20,80}$/.test(id)) throw new Error('Invalid folder id'); db.removeSelectedFolder(id); db.audit('folder_removed', id); return folderStatus(); });
  ipcMain.handle('set-folder-tracking-enabled', (_e, enabled: unknown) => { if (typeof enabled !== 'boolean') throw new Error('Invalid folder setting'); db.setSetting('folderTrackingEnabled', String(enabled)); return folderStatus(); });
  ipcMain.handle('clear-folder-context', () => { db.clearFolderContext(); db.audit('folder_context_cleared'); return folderStatus(); });
  ipcMain.handle('search-similar-memories', async (_e, query: unknown, limit?: unknown, threshold?: unknown) => { if (typeof query !== 'string' || !query.trim() || query.length > 500 || /[\u0000-\u001f]/.test(query)) throw new Error('Invalid semantic query'); const safeLimit = limit === undefined ? 10 : Number(limit); const safeThreshold = threshold === undefined ? 0.15 : Number(threshold); if (!Number.isInteger(safeLimit) || safeLimit < 1 || safeLimit > 20) throw new Error('Invalid semantic result limit'); if (!Number.isFinite(safeThreshold) || safeThreshold < 0 || safeThreshold > 1) throw new Error('Invalid semantic threshold'); if (db.setting('semanticMemoryEnabled', 'true') !== 'true') return []; const memories = db.memories(); await semanticMemory.indexMemories(memories, 20); return semanticMemory.searchSimilarMemories(query, memories, safeLimit, safeThreshold); });
  ipcMain.handle('test-ai-connection', async () => { if (!aiStatus().enabled) return aiStatus(); if (!llmProvider.isConfigured()) return aiStatus(); try { await llmProvider.generateResponse({ systemPrompt: 'Return a JSON object with an empty responses array.', userPrompt: 'Connection test only.', context: null, memories: [], preferences: [], recommendations: [] }); return { ...aiStatus(), status: 'connected' }; } catch { return { ...aiStatus(), status: 'unavailable' }; } });
  ipcMain.handle('pause', (_e, minutes?: number) => { privacy.pause(minutes); collector.stop(); return state(); });
  ipcMain.handle('resume', () => { privacy.resume(); collector.start(); return state(); });
  ipcMain.handle('setting', (_e, key: string, value: string | boolean) => { if (!['retention','titleCollection','memoryLearning','memoryRetention','aiEnabled','aiProvider','semanticMemoryEnabled','embeddingProvider','localNeuralModel','recommendationsEnabled','recommendationFrequency','maxRecommendationsPerDay','goalProgressEnabled'].includes(key)) throw new Error('Unsupported setting'); if (key === 'aiEnabled' && typeof value !== 'boolean') throw new Error('Invalid AI setting'); if (key === 'semanticMemoryEnabled' && typeof value !== 'boolean') throw new Error('Invalid semantic memory setting'); if (key === 'recommendationsEnabled' && typeof value !== 'boolean') throw new Error('Invalid recommendation setting'); if (key === 'goalProgressEnabled' && typeof value !== 'boolean') throw new Error('Invalid goal setting'); if (key === 'recommendationFrequency' && !['off','low','normal','high'].includes(String(value))) throw new Error('Invalid recommendation frequency'); if (key === 'maxRecommendationsPerDay' && (!/^\d+$/.test(String(value)) || Number(value)<0 || Number(value)>100)) throw new Error('Invalid recommendation limit'); if (key === 'aiProvider' && value !== 'external') throw new Error('Unsupported AI provider'); if (key === 'embeddingProvider' && value !== 'local-deterministic' && value !== 'local-neural') throw new Error('Unsupported embedding provider'); if (key === 'localNeuralModel' && (typeof value !== 'string' || (value !== '' && !/^[A-Za-z0-9._-]{1,80}$/.test(value)))) throw new Error('Invalid local model identifier'); db.setSetting(key, String(value)); if (key === 'embeddingProvider' || key === 'localNeuralModel') configureSemanticMemory(); db.cleanup(); if (key === 'memoryRetention') db.cleanupMemory(); return state(); });
  ipcMain.handle('add-exclusion', (_e, name: string) => { if (!name || name.length > 120) throw new Error('Invalid application'); db.addExclusion(name.trim()); return state(); });
  ipcMain.handle('remove-exclusion', (_e, name: string) => { db.removeExclusion(name); return state(); });
  ipcMain.handle('delete-all-data', () => { db.deleteAll(); return state(); });
  ipcMain.handle('recent-memories', () => memoryState().recentMemories);
  ipcMain.handle('relevant-memories', (_e, topic: string) => memoryEngine.getRelevantMemories(db.memories(), String(topic)));
  ipcMain.handle('project-memories', (_e, project: string) => memoryEngine.getProjectMemories(db.memories(), String(project)));
  ipcMain.handle('top-preferences', (_e, limit?: number) => preferenceEngine.getTopPreferences(db.preferences(), limit ?? 10));
  ipcMain.handle('get-preference-details', (_e, id: unknown) => { if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid preference id'); return db.preferences().find(preference => preference.id === id) ?? null; });
  ipcMain.handle('forget-preference', (_e, id: unknown) => { if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid preference id'); db.forgetPreference(id); return buildPersonalizationSummary(db.preferences(), db.getFeedbackSummary()); });
  ipcMain.handle('get-personalization-summary', () => buildPersonalizationSummary(db.preferences(), db.getFeedbackSummary()));
  ipcMain.handle('get-memory', (_e, name: string) => memoryEngine.getMemory(db.memories(), String(name)));
  ipcMain.handle('delete-memory', (_e, id: string) => { db.deleteMemory(String(id)); return memoryState(); });
  ipcMain.handle('clear-memories', () => { db.clearMemories(); return memoryState(); });
  ipcMain.handle('clear-preferences', () => { db.clearPreferences(); return memoryState(); });
  ipcMain.handle('recommendations', () => db.getRecentRecommendations(20));
  ipcMain.handle('delete-recommendation', (_e, id: string) => { if (typeof id !== 'string' || id.length > 200) throw new Error('Invalid recommendation id'); db.deleteRecommendation(id); return db.getRecentRecommendations(20); });
  ipcMain.handle('clear-recommendations', () => { db.clearRecommendations(); return []; });
  ipcMain.handle('get-feedback-summary', () => db.getFeedbackSummary());
  ipcMain.handle('submit-recommendation-feedback', (_e, id: string, feedback: unknown) => { if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid recommendation id'); const normalized = normalizeFeedback(feedback); if (!normalized) throw new Error('Invalid feedback'); return db.submitRecommendationFeedback(id, normalized); });
  ipcMain.handle('submit-action-feedback', (_e, id: string, feedback: unknown) => { if (typeof id !== 'string' || !/^[A-Za-z0-9:_-]{1,200}$/.test(id)) throw new Error('Invalid action id'); const normalized = normalizeFeedback(feedback); if (!normalized) throw new Error('Invalid feedback'); return db.submitActionFeedback(id, normalized); });
  ipcMain.handle('agent-responses', async () => { const result = await contextAndMemory(); const memories = db.memories(); const ordered = [...result.semanticMatches.map(item => item.memory), ...memories.filter(memory => !result.semanticMatches.some(item => item.memory.id === memory.id))]; return agentEngine.generate(result.context, ordered, db.preferences(), db.getRecentRecommendations(8), AGENT_TOOLS); });
  ipcMain.handle('pending-agent-actions', () => db.getPendingAgentActions());
  ipcMain.handle('approve-agent-action', async (_e, id: string) => { if (typeof id !== 'string' || id.length > 200) throw new Error('Invalid action id'); const action = db.getPendingAgentActions().find(item => item.id === id); if (!action || action.status !== 'pending') return db.getPendingAgentActions(); db.setAgentActionStatus(id, 'approved'); db.audit('action_approved', `${id}:${action.toolName}`); await actionExecutor.execute({ ...action, status: 'approved' }); return db.getPendingAgentActions(); });
  ipcMain.handle('reject-agent-action', (_e, id: string) => { if (typeof id !== 'string' || id.length > 200) throw new Error('Invalid action id'); const action = db.getPendingAgentActions().find(item => item.id === id); if (action?.status === 'pending') { db.setAgentActionStatus(id, 'rejected'); db.audit('action_rejected', `${id}:${action.toolName}`); } return db.getPendingAgentActions(); });
  ipcMain.handle('execute-approved-agent-action', async (_e, id: string) => { if (typeof id !== 'string' || id.length > 200) throw new Error('Invalid action id'); const action = db.getPendingAgentActions().find(item => item.id === id); if (!action) return { status:'missing' }; return actionExecutor.execute(action); });
  ipcMain.handle('clear-agent-actions', () => { db.clearAgentActions(); return []; });
  createWindow(); app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });
}).catch(() => { diagnostics?.record('startup', 'error', 'startup_failed'); app.quit(); });
app.on('before-quit', () => { if (shuttingDown) return; shuttingDown = true; tasks?.stopAll(); connector?.stop(); collector?.stop(); db?.close(); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
