export interface BrowserContextPayload { domain: string; url?: string; title?: string; category?: string; topic?: string; timestamp: string; duration?: number; }
export interface BrowserContextRecord { id: string; domain: string; sanitizedUrl?: string; title?: string; category?: string; topic?: string; timestamp: string; durationSeconds: number; source: 'browser'; }
export interface BrowserDomainRules { allowed: string[]; blocked: string[]; }
const MAX_TITLE = 240;
export function normalizeDomain(value: unknown): string | null { if (typeof value !== 'string') return null; const domain = value.trim().toLowerCase().replace(/^https?:\/\//, '').split('/')[0].split(':')[0]; if (!domain || domain.length > 253 || !/^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(domain)) return null; return domain; }
export function sanitizeUrl(value: unknown, domain: string): string | undefined { if (typeof value !== 'string' || value.length > 2000) return undefined; try { const parsed = new URL(value); if (!['http:', 'https:'].includes(parsed.protocol) || parsed.username || parsed.password) return undefined; const host = normalizeDomain(parsed.hostname); if (!host || host !== domain) return undefined; const path = `/${parsed.pathname.split('/').filter(part => part && part !== '.' && part !== '..').join('/')}`.slice(0, 500); return `${parsed.protocol}//${host}${path === '/' ? '' : path}` || undefined; } catch { return undefined; } }
export function validateBrowserPayload(payload: unknown, rules: BrowserDomainRules, now = Date.now()): BrowserContextRecord | null { if (!payload || typeof payload !== 'object') return null; const raw = payload as Record<string, unknown>; const domain = normalizeDomain(raw.domain); if (!domain || !domainAllowed(domain, rules)) return null; const timestamp = typeof raw.timestamp === 'string' ? Date.parse(raw.timestamp) : NaN; if (!Number.isFinite(timestamp) || Math.abs(now - timestamp) > 7 * 86400000) return null; const duration = raw.duration === undefined ? 0 : Number(raw.duration); if (!Number.isFinite(duration) || duration < 0 || duration > 86400) return null; const title = typeof raw.title === 'string' && raw.title.trim() ? raw.title.trim().slice(0, MAX_TITLE) : undefined; const category = typeof raw.category === 'string' ? raw.category.trim().slice(0, 100) || undefined : undefined; const topic = typeof raw.topic === 'string' ? raw.topic.trim().slice(0, 120) || undefined : undefined; return { id: `browser:${domain}:${timestamp}`, domain, sanitizedUrl: sanitizeUrl(raw.url, domain), title, category, topic, timestamp: new Date(timestamp).toISOString(), durationSeconds: Math.round(duration), source: 'browser' }; }
export function domainAllowed(domain: string, rules: BrowserDomainRules) { const matches = (items: string[]) => items.some(rule => domain === rule || domain.endsWith(`.${rule}`)); return !matches(rules.blocked) && (rules.allowed.length === 0 || matches(rules.allowed)); }
export function normalizeDomainRules(value: unknown): BrowserDomainRules { const raw = value && typeof value === 'object' ? value as Record<string, unknown> : {}; const clean = (item: unknown) => Array.isArray(item) ? [...new Set(item.map(normalizeDomain).filter((x): x is string => Boolean(x)))].slice(0, 100) : []; return { allowed: clean(raw.allowed), blocked: clean(raw.blocked) }; }
