import { ActivitySummary, CurrentContext, DetectedProject } from './shared/contracts';
import { TopicExtractor, TopicSignal } from './topic-extractor';
import { CategoryClassifier } from './category-classifier';
import { ProjectDetector } from './project-detector';
import { correlateActivities, SOURCE_WEIGHTS, CorrelationResult, canonicalTechnology, isFresh } from './unified-context';

function sourceWeight(activity: ActivitySummary) { return activity.source === 'folder' ? .45 : activity.source === 'browser' ? .65 : 1; }
const clamp = (value: number) => Math.max(0, Math.min(1, value));

export class ContextEngine {
  constructor(private topics = new TopicExtractor(), private categories = new CategoryClassifier(), private projects = new ProjectDetector()) {}
  build(activities: ActivitySummary[], now = Date.now()): CurrentContext | null {
    const usable = this.deduplicateSameSource(activities);
    const suppressedBeforeCorrelation = Math.max(0, activities.length - usable.length);
    const windowed = usable.filter(a => { const timestamp = Date.parse(a.endedAt ?? a.startedAt); const source = a.source === 'browser' ? 'browser' : a.source === 'folder' ? 'folder' : 'desktop'; return Number.isFinite(timestamp) && isFresh(source, new Date(timestamp).toISOString(), now); }).sort((a, b) => sourceWeight(b) - sourceWeight(a) || Date.parse(b.endedAt ?? b.startedAt) - Date.parse(a.endedAt ?? a.startedAt)).slice(0, 60);
    if (!windowed.length) return null;
    const topicSignals = this.topics.extract(windowed);
    const category = this.resolveCategory(windowed, topicSignals);
    const project = this.resolveProject(windowed);
    const main = topicSignals[0];
    const technologies = [...new Set(topicSignals.slice(0, 8).map(t => t.technology).filter(Boolean) as string[])].map(canonicalTechnology);
    const initialConfidence = this.contextConfidence(category.confidence, main, project, windowed);
    const correlation = correlateActivities(windowed, { category: category.name, topic: main?.name, project: project?.name, technologies }, now);
    const confidence = this.correlatedConfidence(initialConfidence, correlation);
    const sourceTypes = correlation.sourceTypes;
    const transitions = this.transitions(windowed);
    const evidence = this.evidence(windowed, main, project, correlation);
    return { category: category.name, parentCategory: category.parent, topic: main?.name ?? null, subtopic: topicSignals.find(t => t.subtopic)?.subtopic ?? null, project: project?.name ?? null, technologies, confidence, evidence, recentTopics: topicSignals.slice(0, 6).map(t => t.name), sourceTypes, confidenceSignals: this.confidenceSignals(correlation, suppressedBeforeCorrelation), sessionId: correlation.sessionId, sessionStart: correlation.sessionStart, sessionEnd: correlation.sessionEnd, transitions, evidenceDurationSeconds: this.effectiveDuration(windowed), };
  }
  correlate(activities: ActivitySummary[], context: Pick<CurrentContext, 'category' | 'topic' | 'project' | 'technologies'>, now = Date.now()) { return correlateActivities(activities, { category: context.category, topic: context.topic ?? undefined, project: context.project ?? undefined, technologies: context.technologies }, now); }
  private deduplicateSameSource(activities: ActivitySummary[]) { const seen = new Set<string>(); return activities.slice(0, 120).filter(activity => { const source = activity.source ?? 'foreground'; const key = `${source}|${activity.application.slice(0, 100).toLowerCase()}|${(activity.title ?? '').slice(0, 160).toLowerCase()}|${(activity.startedAt ?? '').slice(0, 16)}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
  private resolveCategory(activities: ActivitySummary[], signals: TopicSignal[]) { const classifier = this.categories.classify(activities); const candidates = new Map<string, number>(); for (const signal of signals.slice(0, 8)) if (signal.category) candidates.set(signal.category, (candidates.get(signal.category) ?? 0) + signal.score); const best = [...candidates.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0]; if (!best || best[1] < 2) return classifier; const agreement = activities.filter(activity => `${activity.application} ${activity.title ?? ''}`.toLowerCase().includes(best[0].toLowerCase())).length; return best[0] === classifier.name || agreement >= 2 ? { name: best[0], parent: classifier.parent, confidence: Math.max(classifier.confidence, Math.min(.98, .55 + best[1] / 20)) } : classifier; }
  private resolveProject(activities: ActivitySummary[]): DetectedProject | null { const detected = this.projects.detect(activities); const folder = activities.find(activity => activity.source === 'folder' && /^Folder:\s*/i.test(activity.application)); const label = folder?.application.replace(/^Folder:\s*/i, '').trim().slice(0, 120); if (folder && label && !/^(selected|folder|documents|downloads|desktop)$/i.test(label) && (!detected || detected.confidence < .7)) return { id: `project:${label.toLowerCase()}`, name: label, confidence: .62, firstSeen: folder.startedAt, lastSeen: folder.endedAt ?? folder.startedAt, totalSeconds: folder.durationSeconds }; return detected; }
  private correlatedConfidence(initial: number, correlation: CorrelationResult) { const weightedSources = correlation.sourceTypes.reduce((sum, source) => sum + SOURCE_WEIGHTS[source], 0); const sourceCoverage = Math.min(1, weightedSources / 1.8); return clamp(initial * .35 + sourceCoverage * .2 + correlation.agreement * .2 + correlation.durationScore * .1 + correlation.temporalProximity * .1 + Math.max(correlation.projectConsistency, correlation.topicConsistency, correlation.technologyConsistency) * .05); }
  private confidenceSignals(correlation: CorrelationResult, suppressedBeforeCorrelation = 0) { const signals: string[] = [`${correlation.sourceTypes.length} source${correlation.sourceTypes.length === 1 ? '' : 's'} contributed`]; if (correlation.agreement >= .5) signals.push('source agreement'); if (correlation.temporalProximity >= .7) signals.push('temporal proximity'); if (correlation.durationScore >= .5) signals.push('sustained duration'); if (correlation.projectConsistency >= .5) signals.push('project consistency'); if (correlation.technologyConsistency >= .5) signals.push('technology agreement'); if (correlation.deduplicatedCount || suppressedBeforeCorrelation) signals.push('duplicate observations suppressed'); return signals.slice(0, 8); }
  private contextConfidence(category: number, topic: TopicSignal | undefined, project: DetectedProject | null, activities: ActivitySummary[]) { let value = category * .45 + (topic ? .35 : 0) + (project ? project.confidence * .2 : 0); if (activities.length > 1) value += .05; return Math.min(.99, Math.max(.2, value)); }
  private evidence(activities: ActivitySummary[], topic: TopicSignal | undefined, project: DetectedProject | null, correlation: CorrelationResult) { const total = Math.round(this.effectiveDuration(activities) / 60); const items = [`${activities[0].application} activity observed for approximately ${total} minutes`]; if (topic) items.push(`${topic.name} detected from structured activity signals`); if (project) items.push(`Project candidate ${project.name} supported by structured metadata`); if (correlation.sourceTypes.length > 1) items.push(`${correlation.sourceTypes.length} sources agree within a bounded time window`); if (correlation.deduplicatedCount) items.push(`${correlation.deduplicatedCount} duplicate observation${correlation.deduplicatedCount === 1 ? '' : 's'} suppressed`); return items; }
  private effectiveDuration(activities: ActivitySummary[]) { const durations = activities.map(activity => Math.max(0, activity.durationSeconds)); return Math.min(90 * 60, Math.max(...durations, Math.min(30 * 60, durations.reduce((sum, value) => sum + value, 0)))); }
  private transitions(activities: ActivitySummary[]) { const ordered = [...activities].sort((a, b) => Date.parse(a.startedAt) - Date.parse(b.startedAt)); const result: string[] = []; let previous = ''; for (const activity of ordered) { const source = activity.source ?? 'foreground'; const marker = source === 'browser' ? 'Browser research' : source === 'folder' ? 'Folder work' : activity.application.slice(0, 60); if (previous && previous !== marker) result.push(`${previous} → ${marker}`); previous = marker; } return [...new Set(result)].slice(0, 8); }
}
