import { FeedbackSummary, MemoryRecord, PendingAgentAction, PreferenceRecord, Recommendation, SemanticMemoryStatus } from './shared/contracts';

export type LineageSource = 'Desktop' | 'Browser' | 'Folder' | 'Memory' | 'Preference' | 'Semantic' | 'Feedback';
export interface LineageItem { sourceType: LineageSource; sourceRecordId?: string; category?: string; topic?: string; project?: string; technology?: string; evidenceCount?: number; coarseTimeBucket?: string; reason: string; }
export interface MemoryExplanation { memory: { id: string; name: string; category: string; strength: number; confidence: number }; evidenceCount: number; distinctDays: number; projects: string[]; technologies: string[]; recent: boolean; sources: LineageSource[]; why: string; lineage: LineageItem[]; }
export interface PreferenceExplanation { preference: PreferenceRecord; sources: LineageSource[]; projects: string[]; technologies: string[]; feedbackInfluence: number; why: string; lineage: LineageItem[]; }
export interface RecommendationExplanation { recommendation: { id: string; title: string; score: number; confidence: number }; signals: string[]; sourceTypes: LineageSource[]; feedback: string; why: string; lineage: LineageItem[]; }
export function explainContext(context: import('./shared/contracts').CurrentContext) { return { category: context.category.slice(0, 100), topic: context.topic?.slice(0, 120) ?? null, project: context.project?.slice(0, 120) ?? null, technologies: bounded(context.technologies, 8), sources: (context.sourceTypes ?? ['desktop']).slice(0, 3), confidence: Math.max(0, Math.min(1, context.confidence)), signals: bounded(context.confidenceSignals ?? [], 8), durationSeconds: Math.max(0, Math.min(5400, context.evidenceDurationSeconds ?? 0)), transitions: bounded(context.transitions ?? [], 8), why: context.evidence.slice(0, 4).map(item => item.slice(0, 180)).join(' ') }; }

const bounded = (items: string[], max = 12) => [...new Set(items.filter(item => typeof item === 'string' && item.length > 0).map(item => item.slice(0, 100)))].slice(0, max);
const parse = (value: string): Record<string, unknown> => { try { const parsed = JSON.parse(value); return parsed && typeof parsed === 'object' ? parsed as Record<string, unknown> : {}; } catch { return {}; } };
const strings = (value: unknown) => Array.isArray(value) ? bounded(value.filter(item => typeof item === 'string') as string[]) : [];
const sources = (value: string | undefined): LineageSource[] => { const lower = (value ?? '').toLowerCase(); const result: LineageSource[] = []; if (lower.includes('browser')) result.push('Browser'); if (lower.includes('folder')) result.push('Folder'); if (lower.includes('desktop') || lower.includes('foreground') || lower.includes('context')) result.push('Desktop'); return result.length ? result : ['Desktop']; };

export function explainMemory(memory: MemoryRecord, now = Date.now()): MemoryExplanation {
  const metadata = parse(memory.metadataJson); const projects = strings(metadata.projects); const technologies = strings(metadata.technologies); const observedDays = strings(metadata.observedDays); const recent = Number.isFinite(Date.parse(memory.lastSeen)) && now - Date.parse(memory.lastSeen) <= 7 * 86400000; const sourceTypes = Array.isArray(metadata.sourceTypes) ? metadata.sourceTypes.filter(item => item === 'desktop' || item === 'browser' || item === 'folder').map(item => item === 'desktop' ? 'Desktop' : item === 'browser' ? 'Browser' : 'Folder') as LineageSource[] : sources(memory.source); const lineage = sourceTypes.map(sourceType => ({ sourceType, sourceRecordId: memory.id, category: memory.category, topic: memory.type === 'topic' ? memory.name : undefined, project: projects[0], technology: technologies[0], evidenceCount: Math.min(10000, Math.max(0, Math.round(memory.evidenceCount))), coarseTimeBucket: recent ? 'recent' : 'older', reason: 'Aggregate evidence contributed to this memory.' }));
  const why = `Repeated observations across ${Math.max(1, observedDays.length)} day${observedDays.length === 1 ? '' : 's'}${sourceTypes.length ? ` from ${sourceTypes.join(' and ')}` : ''}.`;
  return { memory: { id: memory.id, name: memory.name.slice(0, 120), category: memory.category.slice(0, 120), strength: Math.max(0, Math.min(1, memory.strength)), confidence: Math.max(0, Math.min(1, memory.confidence)) }, evidenceCount: Math.min(10000, Math.max(0, Math.round(memory.evidenceCount))), distinctDays: Math.min(180, Math.max(0, observedDays.length || 1)), projects, technologies, recent, sources: sourceTypes, why, lineage };
}

export function explainPreference(preference: PreferenceRecord): PreferenceExplanation {
  const sourceTypes: LineageSource[] = (preference.sourceTypes ?? ['Memory']).map(value => value === 'desktop' ? 'Desktop' : value === 'browser' ? 'Browser' : value === 'folder' ? 'Folder' : 'Memory') as LineageSource[]; const feedbackInfluence = Math.min(100, Math.max(0, preference.feedbackEvidence ?? 0)); const why = preference.evidenceSummary ? preference.evidenceSummary.slice(0, 240) : `Repeated evidence across ${Math.max(1, preference.distinctDays ?? 1)} distinct days.`; const lineage = [{ sourceType: 'Preference' as const, sourceRecordId: preference.id, category: preference.category, topic: preference.name, evidenceCount: Math.min(10000, Math.max(0, Math.round(preference.evidenceCount))), reason: 'Preference was derived from repeated memory evidence.' }]; return { preference: { ...preference, name: preference.name.slice(0, 120), category: preference.category.slice(0, 120), evidenceSummary: preference.evidenceSummary?.slice(0, 240) }, sources: sourceTypes, projects: bounded(preference.projects ?? []), technologies: bounded(preference.technologies ?? []), feedbackInfluence, why, lineage };
}

export function explainRecommendation(recommendation: Recommendation, feedback: FeedbackSummary): RecommendationExplanation {
  const signals = recommendation.signals ?? ['Current context', 'Preference', 'Memory', 'Recency']; const sourceTypes: LineageSource[] = ['Desktop']; if (recommendation.sourceContext.toLowerCase().includes('browser')) sourceTypes.push('Browser'); if (recommendation.sourceContext.toLowerCase().includes('folder')) sourceTypes.push('Folder'); const counts = feedback.byType[recommendation.type]; const feedbackText = counts ? `Useful ${counts.useful}, not useful ${counts.not_useful}, dismissed ${counts.dismissed}, ignored ${counts.ignored}.` : 'No direct feedback recorded.'; return { recommendation: { id: recommendation.id, title: recommendation.title.slice(0, 200), score: Math.max(0, Math.min(100, recommendation.score)), confidence: Math.max(0, Math.min(1, recommendation.confidence)) }, signals: bounded(signals, 8), sourceTypes: [...new Set(sourceTypes)], feedback: feedbackText, why: recommendation.reason.slice(0, 300), lineage: [{ sourceType: 'Memory', sourceRecordId: recommendation.id, category: recommendation.category, topic: recommendation.topic ?? undefined, project: recommendation.project ?? undefined, reason: 'Application-owned recommendation signals.' }, { sourceType: 'Feedback', sourceRecordId: recommendation.id, reason: feedbackText }] };
}

export function explainSemantic(status: SemanticMemoryStatus) { return { provider: status.provider.slice(0, 80), model: status.model.slice(0, 120), dimensions: Math.max(0, Math.min(4096, status.dimensions)), available: status.available, indexedMemoryCount: Math.max(0, Math.min(100000, status.indexedMemoryCount)) }; }
export function explainAction(action: PendingAgentAction) { return { id: action.id, toolName: action.toolName.slice(0, 80), status: action.status, reason: action.reason.slice(0, 240), sourceContext: action.sourceContext.slice(0, 240), createdAt: action.createdAt, approvedAt: action.approvedAt, completedAt: action.completedAt, hasError: Boolean(action.error) }; }
