export interface SelectedFolder { id: string; label: string; path: string; enabled: boolean; lastScanAt?: string; fileCount?: number; }
export interface FolderFileEntry { relativePath: string; name: string; extension: string; size: number; modifiedAt: string; }
export interface FolderScanOptions { maxFiles?: number; maxDepth?: number; maxNameLength?: number; ignoredDirectories?: string[]; }
export interface FolderFileSystem { list(directory: string): Promise<Array<{ name: string; isDirectory: boolean; size: number; modifiedAt: string }>>; }
export const DEFAULT_IGNORED_DIRECTORIES = ['.git', 'node_modules', 'dist', 'build', 'coverage', '.venv', 'target'];
export function isSensitiveFilename(name: string) { return name === '.env' || /^\.env\./i.test(name) || /^(credentials?|secrets?|password)[^/]*$/i.test(name) || /\.(pem|key)$/i.test(name); }
export function normalizeRelativePath(value: string) { return value.replace(/\\/g, '/').split('/').filter(part => part && part !== '.' && part !== '..').join('/').slice(0, 500); }
export async function scanSelectedFolder(folder: SelectedFolder, fs: FolderFileSystem, options: FolderScanOptions = {}): Promise<FolderFileEntry[]> { const maxFiles = Math.max(1, Math.min(1000, options.maxFiles ?? 500)); const maxDepth = Math.max(0, Math.min(12, options.maxDepth ?? 5)); const maxNameLength = Math.max(20, Math.min(255, options.maxNameLength ?? 160)); const ignored = new Set((options.ignoredDirectories ?? DEFAULT_IGNORED_DIRECTORIES).map(item => item.toLowerCase())); const output: FolderFileEntry[] = []; async function visit(directory: string, relative: string, depth: number): Promise<void> { if (output.length >= maxFiles || depth > maxDepth) return; let entries: Array<{ name: string; isDirectory: boolean; size: number; modifiedAt: string }>; try { entries = await fs.list(directory); } catch { return; } for (const entry of entries.sort((a,b) => a.name.localeCompare(b.name))) { if (output.length >= maxFiles || entry.name.length > maxNameLength || isSensitiveFilename(entry.name)) continue; const childRelative = normalizeRelativePath(relative ? `${relative}/${entry.name}` : entry.name); if (!childRelative) continue; if (entry.isDirectory) { if (!ignored.has(entry.name.toLowerCase())) await visit(`${directory}/${entry.name}`, childRelative, depth + 1); } else output.push({ relativePath: childRelative, name: entry.name, extension: extension(entry.name), size: Math.max(0, Math.min(entry.size, 1024 * 1024 * 1024)), modifiedAt: entry.modifiedAt }); } } await visit(folder.path, '', 0); return output; }
function extension(name: string) { const index = name.lastIndexOf('.'); return index > 0 ? name.slice(index + 1).toLowerCase().slice(0, 20) : ''; }
