import { MEMORY_RELATIONSHIPS } from './memory-relationships';
import { canonicalMemoryConcept } from './memory-canonicalization';
import { MemoryRecord } from './shared/contracts';
export interface ConceptCluster { root: string; concepts: string[]; relationships: Array<{ from: string; to: string; strength: number }>; }
export function buildConceptCluster(root: string, memories: MemoryRecord[], maxConcepts = 12, maxDepth = 2): ConceptCluster {
  const safeLimit = Math.max(1, Math.min(20, Math.floor(maxConcepts))); const safeDepth = Math.max(0, Math.min(2, Math.floor(maxDepth))); const byName = new Map(memories.map(memory => [canonicalMemoryConcept(memory.name).toLowerCase(), memory])); const queue: Array<{ name: string; depth: number }> = [{ name: canonicalMemoryConcept(root), depth: 0 }]; const concepts: string[] = []; const relationships: Array<{ from: string; to: string; strength: number }> = []; const seen = new Set<string>();
  while (queue.length && concepts.length < safeLimit) { const item = queue.shift()!; const key = item.name.toLowerCase(); if (seen.has(key) || item.depth > safeDepth) continue; seen.add(key); concepts.push(item.name); const mapping = MEMORY_RELATIONSHIPS.find(value => canonicalMemoryConcept(value.name).toLowerCase() === key); for (const related of mapping?.related ?? []) { if (concepts.length + queue.length >= safeLimit * 2) break; const canonical = canonicalMemoryConcept(related); const memory = byName.get(canonical.toLowerCase()); const strength = memory ? Math.min(1, Math.max(.05, memory.strength * memory.confidence)) : .25; relationships.push({ from: item.name, to: canonical, strength }); if (item.depth < safeDepth && !seen.has(canonical.toLowerCase())) queue.push({ name: canonical, depth: item.depth + 1 }); } }
  return { root: canonicalMemoryConcept(root), concepts: [...new Set(concepts)].slice(0, safeLimit), relationships: relationships.slice(0, 30).sort((a, b) => b.strength - a.strength || a.from.localeCompare(b.from) || a.to.localeCompare(b.to)) };
}
