import { FeedbackSummary, MemoryRecord, PreferenceRecord, PreferenceTrend, TimeBucket, TimePatternSummary } from './shared/contracts';

const clamp = (value: number, min = 0, max = 1) => Math.min(max, Math.max(min, value));
const DAY = 86400000;

export class PreferenceEngine {
  update(existing: PreferenceRecord[], memories: MemoryRecord[], updatedAt: string, feedback?: FeedbackSummary, semanticSupport: Record<string, number> = {}): PreferenceRecord[] {
    const now = Date.parse(updatedAt); const byName = new Map(existing.map(preference => [preference.name.toLowerCase(), { ...preference }]));
    for (const preference of byName.values()) {
      const ageDays = Math.max(0, (now - Date.parse(preference.lastSeen)) / DAY); const factor = Math.pow(0.5, ageDays / 90); preference.strength = clamp(preference.strength * factor); preference.confidence = clamp(preference.confidence * (0.92 + 0.08 * factor)); preference.trend = ageDays > 90 ? 'inactive' : preference.trend ?? 'stable'; preference.updatedAt = updatedAt;
    }
    for (const memory of memories.filter(item => ['topic', 'category', 'technology', 'project'].includes(item.type) && item.evidenceCount >= 2)) {
      const metadata = safeMetadata(memory.metadataJson); const distinctDays = distinctDayCount(metadata, memory); const feedbackStats = this.feedbackFor(memory, feedback); const previous = byName.get(memory.name.toLowerCase()); const evidenceScore = 1 - Math.exp(-memory.evidenceCount / 5); const durationScore = 1 - Math.exp(-memory.totalSeconds / 36000); const distinctScore = Math.min(1, distinctDays / 6); const recency = recencyScore(memory.lastSeen, now); const consistency = consistencyScore(metadata, distinctDays); const sourceTypes = stringList(metadata.sourceTypes); const sourceDiversity = Math.min(1, sourceTypes.length / 3); const projects = stringList(metadata.projects); const projectContinuity = Math.min(1, projects.length / 3); const confidence = clamp(evidenceScore * .22 + durationScore * .18 + distinctScore * .2 + recency * .18 + consistency * .12 + sourceDiversity * .05 + projectContinuity * .05 + Math.min(.02, feedbackStats.total / 150)); const feedbackAdjustment = Math.max(-.05, Math.min(.05, (feedbackStats.useful * .02 - feedbackStats.notUseful * .02 - feedbackStats.dismissed * .012 - feedbackStats.ignored * .006) / Math.max(1, feedbackStats.total))); const semanticAdjustment = Math.min(.02, Math.max(0, Number(semanticSupport[memory.name]) || 0) * .02); const strength = clamp(memory.strength * .55 + evidenceScore * .2 + durationScore * .1 + distinctScore * .1 + recency * .05 + feedbackAdjustment + semanticAdjustment); const preference: PreferenceRecord = { id: previous?.id ?? `preference:${memory.name.toLowerCase()}`, name: memory.name, category: memory.category, sourceType: memory.type, strength, confidence, firstSeen: previous?.firstSeen ?? memory.firstSeen, lastSeen: memory.lastSeen, evidenceCount: memory.evidenceCount, totalSeconds: memory.totalSeconds, updatedAt, distinctDays, trend: trendFor(memory, previous, now), evidenceSummary: evidenceSummary(memory, distinctDays, recency, metadata), timePattern: timePattern(metadata), feedbackEvidence: feedbackStats.total, projects, technologies: stringList(metadata.technologies), sourceTypes, projectContinuity };
      byName.set(memory.name.toLowerCase(), preference);
    }
    return [...byName.values()];
  }
  getTopPreferences(preferences: PreferenceRecord[], limit = 10) { return [...preferences].sort((a,b) => (b.strength * b.confidence) - (a.strength * a.confidence) || b.evidenceCount - a.evidenceCount || a.name.localeCompare(b.name)).slice(0, limit); }
  getPreference(preferences: PreferenceRecord[], name: string) { return preferences.find(p => p.name.toLowerCase() === name.toLowerCase()) ?? null; }
  getRisingPreferences(preferences: PreferenceRecord[], limit = 10) { return this.getTopPreferences(preferences.filter(p => p.trend === 'rising' || p.trend === 'new'), limit); }
  getDecliningPreferences(preferences: PreferenceRecord[], limit = 10) { return this.getTopPreferences(preferences.filter(p => p.trend === 'declining' || p.trend === 'inactive'), limit); }
  private feedbackFor(memory: MemoryRecord, feedback?: FeedbackSummary) { const empty = { useful: 0, notUseful: 0, dismissed: 0, ignored: 0, total: 0 }; if (!feedback) return empty; const buckets = [feedback.byTopic[memory.name], feedback.byCategory[memory.category]].filter(Boolean); const result = { ...empty }; for (const bucket of buckets) { result.useful += bucket.useful; result.notUseful += bucket.not_useful; result.dismissed += bucket.dismissed; result.ignored += bucket.ignored; } result.total = result.useful + result.notUseful + result.dismissed + result.ignored; return result; }
}
function safeMetadata(value: string): Record<string, unknown> { try { const parsed = JSON.parse(value); return parsed && typeof parsed === 'object' ? parsed as Record<string, unknown> : {}; } catch { return {}; } }
function distinctDayCount(metadata: Record<string, unknown>, memory: MemoryRecord) { return Array.isArray(metadata.observedDays) ? new Set(metadata.observedDays.filter(item => typeof item === 'string')).size : (memory.firstSeen.slice(0, 10) === memory.lastSeen.slice(0, 10) ? 1 : 2); }
function recencyScore(lastSeen: string, now: number) { const age = Math.max(0, (now - Date.parse(lastSeen)) / DAY); return Math.max(0, Math.min(1, 1 - age / 90)); }
function consistencyScore(metadata: Record<string, unknown>, distinctDays: number) { const daily = metadata.dailyEvidence && typeof metadata.dailyEvidence === 'object' ? Object.values(metadata.dailyEvidence as Record<string, unknown>).filter(value => typeof value === 'number') as number[] : []; if (daily.length < 2) return Math.min(1, distinctDays / 6); const mean = daily.reduce((sum, value) => sum + value, 0) / daily.length; const variance = daily.reduce((sum, value) => sum + Math.pow(value - mean, 2), 0) / daily.length; return Math.max(0, Math.min(1, 1 - Math.sqrt(variance) / Math.max(1, mean))); }
function trendFor(memory: MemoryRecord, previous: PreferenceRecord | undefined, now: number): PreferenceTrend { const metadata = safeMetadata(memory.metadataJson); const age = Math.max(0, (now - Date.parse(memory.lastSeen)) / DAY); if (age > 90) return 'inactive'; if (memory.evidenceCount <= 2 && !previous) return 'new'; const daily = metadata.dailyEvidence && typeof metadata.dailyEvidence === 'object' ? metadata.dailyEvidence as Record<string, unknown> : {}; const cutoff = new Date(now - 14 * DAY).toISOString().slice(0, 10); const oldCutoff = new Date(now - 28 * DAY).toISOString().slice(0, 10); let recent = 0; let prior = 0; for (const [date, value] of Object.entries(daily)) { if (typeof value !== 'number') continue; if (date >= cutoff) recent += value; else if (date >= oldCutoff) prior += value; } if (recent > 0 && recent > prior * 1.25) return 'rising'; if (prior > 0 && recent < prior * .75) return 'declining'; return previous?.trend === 'new' ? 'stable' : 'stable'; }
function timePattern(metadata: Record<string, unknown>): TimePatternSummary { const buckets = metadata.timeBuckets && typeof metadata.timeBuckets === 'object' ? metadata.timeBuckets as Record<string, unknown> : {}; const values = Object.entries(buckets).filter(([, value]) => typeof value === 'number').sort((a,b) => Number(b[1]) - Number(a[1])); const primaryBucket = values[0]?.[0] as TimeBucket | undefined; const weekday = Number(metadata.weekdayEvidence) || 0; const weekend = Number(metadata.weekendEvidence) || 0; const total = weekday + weekend; const short = Number(metadata.shortSessions) || 0; const long = Number(metadata.longSessions) || 0; return { primaryBucket, weekdayRatio: total ? weekday / total : 0, weekendRatio: total ? weekend / total : 0, sessionShape: short && long ? 'mixed' : short ? 'short' : long ? 'long' : 'unknown' }; }
function stringList(value: unknown): string[] { return Array.isArray(value) ? value.filter(item => typeof item === 'string').map(item => item.slice(0, 100)).slice(0, 30) : []; }
function evidenceSummary(memory: MemoryRecord, distinctDays: number, recency: number, metadata: Record<string, unknown>) { const hours = (memory.totalSeconds / 3600).toFixed(1); const sessions = Number(metadata.sessionCount) || Math.max(1, Math.round(memory.evidenceCount)); const parts = [`observed repeatedly`, `${sessions} sessions`, `${hours} hours total`, `active across ${distinctDays} different days`]; if (recency >= .5) parts.push('recent activity detected'); const projects = Array.isArray(metadata.projects) ? metadata.projects.filter(item => typeof item === 'string') : []; if (projects.length) parts.push('related project activity detected'); return parts.join('; '); }
