import { ActivitySummary } from './shared/contracts';

export type UnifiedSource = 'desktop' | 'browser' | 'folder';
export const SOURCE_WEIGHTS: Record<UnifiedSource, number> = { desktop: 1, browser: .65, folder: .45 };
export interface NormalizedObservation { source: UnifiedSource; sourceId: string; timestamp: string; durationSeconds: number; category?: string; topic?: string; subtopic?: string; project?: string; technologies: string[]; confidence: number; }
export interface CorrelationResult { observations: NormalizedObservation[]; sourceTypes: UnifiedSource[]; deduplicatedCount: number; agreement: number; temporalProximity: number; durationScore: number; projectConsistency: number; technologyConsistency: number; topicConsistency: number; sessionId: string; sessionStart: string; sessionEnd: string; stale: boolean; }

const clean = (value: unknown, max: number) => typeof value === 'string' ? value.trim().slice(0, max) : undefined;
const canonical = (value: string) => { const key = value.trim().toLowerCase(); const aliases: Record<string, string> = { js: 'JavaScript', javascript: 'JavaScript', ts: 'TypeScript', typescript: 'TypeScript', 'godot engine': 'Godot', gdscript: 'GDScript', 'nodejs': 'Node.js', node: 'Node.js', cpp: 'C++', 'c plus plus': 'C++', git: 'Git' }; return aliases[key] ?? value.trim().slice(0, 60); };
const sourceOf = (value?: string): UnifiedSource => value === 'browser' ? 'browser' : value === 'folder' ? 'folder' : 'desktop';
const normSet = (values: string[]) => new Set(values.map(value => value.toLowerCase()));
const ratio = (value: number, max: number) => Math.max(0, Math.min(1, value / Math.max(1, max)));

export function normalizeActivities(activities: ActivitySummary[], now = Date.now()): NormalizedObservation[] {
  const normalized = activities.slice(0, 100).map((activity): NormalizedObservation | null => { const source = sourceOf(activity.source); const timestamp = activity.endedAt ?? activity.startedAt; const parsed = Date.parse(timestamp); if (!Number.isFinite(parsed)) return null; const age = now - parsed; return { source, sourceId: String(activity.id).slice(0, 200), timestamp: new Date(parsed).toISOString(), durationSeconds: Math.max(0, Math.min(86400, Math.round(Number(activity.durationSeconds) || 0))), technologies: [], confidence: age <= freshnessWindow(source) ? 1 : 0 }; }).filter((item): item is NormalizedObservation => Boolean(item));
  return normalized.filter((item): item is NormalizedObservation => item !== null);
}
export function freshnessWindow(source: UnifiedSource): number { return source === 'desktop' ? 60 * 60 * 1000 : source === 'browser' ? 15 * 60 * 1000 : 30 * 60 * 1000; }
export function isFresh(source: UnifiedSource, timestamp: string, now = Date.now()) { return now - Date.parse(timestamp) <= freshnessWindow(source); }
export function canonicalTechnology(value: string) { return canonical(value); }
export function correlateActivities(activities: ActivitySummary[], fields: { category?: string; topic?: string; project?: string; technologies?: string[] }, now = Date.now()): CorrelationResult {
  const normalized = normalizeActivities(activities, now); const seen = new Set<string>(); const observations = normalized.filter(item => { const activity = activities.find(candidate => String(candidate.id).slice(0, 200) === item.sourceId); const app = activity?.application?.toLowerCase().slice(0, 80) ?? ''; const title = activity?.title?.toLowerCase().slice(0, 120) ?? ''; const key = `${item.source}|${app}|${title}|${item.timestamp.slice(0, 16)}`; if (seen.has(key)) return false; seen.add(key); item.category = clean(fields.category, 100); item.topic = clean(fields.topic, 120); item.project = clean(fields.project, 120); item.technologies = [...new Set((fields.technologies ?? []).filter(value => typeof value === 'string').map(canonical))].slice(0, 8); return true; });
  const fresh = observations.filter(item => isFresh(item.source, item.timestamp, now)); const sources = [...new Set(fresh.map(item => item.source))]; const duration = fresh.reduce((sum, item) => sum + item.durationSeconds, 0); const topicCount = fields.topic ? fresh.filter(item => item.topic?.toLowerCase() === fields.topic?.toLowerCase()).length : 0; const projectCount = fields.project ? fresh.filter(item => item.project?.toLowerCase() === fields.project?.toLowerCase()).length : 0; const technologies = fields.technologies ?? []; const technologyCount = technologies.length ? fresh.filter(item => item.technologies.some(value => technologies.map(canonical).includes(value))).length : 0; const timestamps = fresh.map(item => Date.parse(item.timestamp)); const span = timestamps.length ? Math.max(...timestamps) - Math.min(...timestamps) : 0; const agreement = Math.min(1, sources.length / 3 * .55 + ratio(topicCount + projectCount + technologyCount, Math.max(1, fresh.length * 3)) * .45); const temporalProximity = Math.max(0, 1 - span / (15 * 60 * 1000)); const sessionStart = fresh.length ? new Date(Math.min(...timestamps)).toISOString() : new Date(now).toISOString(); const sessionEnd = fresh.length ? new Date(Math.max(...timestamps)).toISOString() : sessionStart; const sessionSpan = Math.min(90 * 60 * 1000, Math.max(0, Date.parse(sessionEnd) - Date.parse(sessionStart))); const sessionId = `session:${sessionStart.slice(0, 16).replace(/[-:]/g, '')}`; return { observations: fresh, sourceTypes: sources, deduplicatedCount: normalized.length - observations.length, agreement, temporalProximity, durationScore: Math.min(1, duration / 1800), projectConsistency: fields.project ? Math.min(1, projectCount / Math.max(1, fresh.length)) : 0, technologyConsistency: technologies.length ? Math.min(1, technologyCount / Math.max(1, fresh.length)) : 0, topicConsistency: fields.topic ? Math.min(1, topicCount / Math.max(1, fresh.length)) : 0, sessionId, sessionStart, sessionEnd: new Date(Date.parse(sessionStart) + sessionSpan).toISOString(), stale: fresh.length === 0 }; }
export function sameSession(a: NormalizedObservation, b: NormalizedObservation): boolean { const gap = Math.abs(Date.parse(a.timestamp) - Date.parse(b.timestamp)); return gap <= 10 * 60 * 1000 && (!a.topic || !b.topic || a.topic.toLowerCase() === b.topic.toLowerCase()) && (!a.project || !b.project || a.project.toLowerCase() === b.project.toLowerCase()); }
